#include <CCBufferTests.h>


CC::BufferTests::UTList CC::BufferTests::GetTests()
{
#pragma warning(suppress : 6262) // Suppress high stack memory usage warning.
    static const UTList tests
    {
        /// Constructor Tests \\\

        ConstructorTests::DefaultConstructor<uint8_t, TestQuantity::None>,
        ConstructorTests::DefaultConstructor<uint16_t, TestQuantity::None>,
        ConstructorTests::DefaultConstructor<uint32_t, TestQuantity::None>,
        ConstructorTests::DefaultConstructor<uint64_t, TestQuantity::None>,
        ConstructorTests::DefaultConstructor<Helper, TestQuantity::None>,
        ConstructorTests::DefaultConstructor<uint8_t, TestQuantity::VeryLow>,
        ConstructorTests::DefaultConstructor<uint16_t, TestQuantity::VeryLow>,
        ConstructorTests::DefaultConstructor<uint32_t, TestQuantity::VeryLow>,
        ConstructorTests::DefaultConstructor<uint64_t, TestQuantity::VeryLow>,
        ConstructorTests::DefaultConstructor<Helper, TestQuantity::VeryLow>,
        ConstructorTests::DefaultConstructor<uint8_t, TestQuantity::High>,
        ConstructorTests::DefaultConstructor<uint16_t, TestQuantity::High>,
        ConstructorTests::DefaultConstructor<uint32_t, TestQuantity::High>,
        ConstructorTests::DefaultConstructor<uint64_t, TestQuantity::High>,
        ConstructorTests::DefaultConstructor<Helper, TestQuantity::High>,

        ConstructorTests::LengthConstructor<uint8_t, TestQuantity::None>,
        ConstructorTests::LengthConstructor<uint16_t, TestQuantity::None>,
        ConstructorTests::LengthConstructor<uint32_t, TestQuantity::None>,
        ConstructorTests::LengthConstructor<uint64_t, TestQuantity::None>,
        ConstructorTests::LengthConstructor<Helper, TestQuantity::None>,
        ConstructorTests::LengthConstructor<uint8_t, TestQuantity::VeryLow>,
        ConstructorTests::LengthConstructor<uint16_t, TestQuantity::VeryLow>,
        ConstructorTests::LengthConstructor<uint32_t, TestQuantity::VeryLow>,
        ConstructorTests::LengthConstructor<uint64_t, TestQuantity::VeryLow>,
        ConstructorTests::LengthConstructor<Helper, TestQuantity::VeryLow>,
        ConstructorTests::LengthConstructor<uint8_t, TestQuantity::High>,
        ConstructorTests::LengthConstructor<uint16_t, TestQuantity::High>,
        ConstructorTests::LengthConstructor<uint32_t, TestQuantity::High>,
        ConstructorTests::LengthConstructor<uint64_t, TestQuantity::High>,
        ConstructorTests::LengthConstructor<Helper, TestQuantity::High>,

        ConstructorTests::PointerCopyConstructorNull<uint8_t, TestQuantity::None>,
        ConstructorTests::PointerCopyConstructorNull<uint16_t, TestQuantity::None>,
        ConstructorTests::PointerCopyConstructorNull<uint32_t, TestQuantity::None>,
        ConstructorTests::PointerCopyConstructorNull<uint64_t, TestQuantity::None>,
        ConstructorTests::PointerCopyConstructorNull<Helper, TestQuantity::None>,
        ConstructorTests::PointerCopyConstructorNull<uint8_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerCopyConstructorNull<uint16_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerCopyConstructorNull<uint32_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerCopyConstructorNull<uint64_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerCopyConstructorNull<Helper, TestQuantity::VeryLow>,
        ConstructorTests::PointerCopyConstructorNull<uint8_t, TestQuantity::High>,
        ConstructorTests::PointerCopyConstructorNull<uint16_t, TestQuantity::High>,
        ConstructorTests::PointerCopyConstructorNull<uint32_t, TestQuantity::High>,
        ConstructorTests::PointerCopyConstructorNull<uint64_t, TestQuantity::High>,
        ConstructorTests::PointerCopyConstructorNull<Helper, TestQuantity::High>,

        ConstructorTests::PointerCopyConstructor<uint8_t, TestQuantity::None>,
        ConstructorTests::PointerCopyConstructor<uint16_t, TestQuantity::None>,
        ConstructorTests::PointerCopyConstructor<uint32_t, TestQuantity::None>,
        ConstructorTests::PointerCopyConstructor<uint64_t, TestQuantity::None>,
        ConstructorTests::PointerCopyConstructor<Helper, TestQuantity::None>,
        ConstructorTests::PointerCopyConstructor<uint8_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerCopyConstructor<uint16_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerCopyConstructor<uint32_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerCopyConstructor<uint64_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerCopyConstructor<Helper, TestQuantity::VeryLow>,
        ConstructorTests::PointerCopyConstructor<uint8_t, TestQuantity::High>,
        ConstructorTests::PointerCopyConstructor<uint16_t, TestQuantity::High>,
        ConstructorTests::PointerCopyConstructor<uint32_t, TestQuantity::High>,
        ConstructorTests::PointerCopyConstructor<uint64_t, TestQuantity::High>,
        ConstructorTests::PointerCopyConstructor<Helper, TestQuantity::High>,

        ConstructorTests::PointerMoveConstructorNull<uint8_t, TestQuantity::None>,
        ConstructorTests::PointerMoveConstructorNull<uint16_t, TestQuantity::None>,
        ConstructorTests::PointerMoveConstructorNull<uint32_t, TestQuantity::None>,
        ConstructorTests::PointerMoveConstructorNull<uint64_t, TestQuantity::None>,
        ConstructorTests::PointerMoveConstructorNull<Helper, TestQuantity::None>,
        ConstructorTests::PointerMoveConstructorNull<uint8_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerMoveConstructorNull<uint16_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerMoveConstructorNull<uint32_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerMoveConstructorNull<uint64_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerMoveConstructorNull<Helper, TestQuantity::VeryLow>,
        ConstructorTests::PointerMoveConstructorNull<uint8_t, TestQuantity::High>,
        ConstructorTests::PointerMoveConstructorNull<uint16_t, TestQuantity::High>,
        ConstructorTests::PointerMoveConstructorNull<uint32_t, TestQuantity::High>,
        ConstructorTests::PointerMoveConstructorNull<uint64_t, TestQuantity::High>,
        ConstructorTests::PointerMoveConstructorNull<Helper, TestQuantity::High>,

        ConstructorTests::PointerMoveConstructor<uint8_t, TestQuantity::None>,
        ConstructorTests::PointerMoveConstructor<uint16_t, TestQuantity::None>,
        ConstructorTests::PointerMoveConstructor<uint32_t, TestQuantity::None>,
        ConstructorTests::PointerMoveConstructor<uint64_t, TestQuantity::None>,
        ConstructorTests::PointerMoveConstructor<Helper, TestQuantity::None>,
        ConstructorTests::PointerMoveConstructor<uint8_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerMoveConstructor<uint16_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerMoveConstructor<uint32_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerMoveConstructor<uint64_t, TestQuantity::VeryLow>,
        ConstructorTests::PointerMoveConstructor<Helper, TestQuantity::VeryLow>,
        ConstructorTests::PointerMoveConstructor<uint8_t, TestQuantity::High>,
        ConstructorTests::PointerMoveConstructor<uint16_t, TestQuantity::High>,
        ConstructorTests::PointerMoveConstructor<uint32_t, TestQuantity::High>,
        ConstructorTests::PointerMoveConstructor<uint64_t, TestQuantity::High>,
        ConstructorTests::PointerMoveConstructor<Helper, TestQuantity::High>,

        ConstructorTests::CopyConstructor<uint8_t, TestQuantity::None>,
        ConstructorTests::CopyConstructor<uint16_t, TestQuantity::None>,
        ConstructorTests::CopyConstructor<uint32_t, TestQuantity::None>,
        ConstructorTests::CopyConstructor<uint64_t, TestQuantity::None>,
        ConstructorTests::CopyConstructor<Helper, TestQuantity::None>,
        ConstructorTests::CopyConstructor<uint8_t, TestQuantity::VeryLow>,
        ConstructorTests::CopyConstructor<uint16_t, TestQuantity::VeryLow>,
        ConstructorTests::CopyConstructor<uint32_t, TestQuantity::VeryLow>,
        ConstructorTests::CopyConstructor<uint64_t, TestQuantity::VeryLow>,
        ConstructorTests::CopyConstructor<Helper, TestQuantity::VeryLow>,
        ConstructorTests::CopyConstructor<uint8_t, TestQuantity::High>,
        ConstructorTests::CopyConstructor<uint16_t, TestQuantity::High>,
        ConstructorTests::CopyConstructor<uint32_t, TestQuantity::High>,
        ConstructorTests::CopyConstructor<uint64_t, TestQuantity::High>,
        ConstructorTests::CopyConstructor<Helper, TestQuantity::High>,

        ConstructorTests::MoveConstructor<uint8_t, TestQuantity::None>,
        ConstructorTests::MoveConstructor<uint16_t, TestQuantity::None>,
        ConstructorTests::MoveConstructor<uint32_t, TestQuantity::None>,
        ConstructorTests::MoveConstructor<uint64_t, TestQuantity::None>,
        ConstructorTests::MoveConstructor<Helper, TestQuantity::None>,
        ConstructorTests::MoveConstructor<uint8_t, TestQuantity::VeryLow>,
        ConstructorTests::MoveConstructor<uint16_t, TestQuantity::VeryLow>,
        ConstructorTests::MoveConstructor<uint32_t, TestQuantity::VeryLow>,
        ConstructorTests::MoveConstructor<uint64_t, TestQuantity::VeryLow>,
        ConstructorTests::MoveConstructor<Helper, TestQuantity::VeryLow>,
        ConstructorTests::MoveConstructor<uint8_t, TestQuantity::High>,
        ConstructorTests::MoveConstructor<uint16_t, TestQuantity::High>,
        ConstructorTests::MoveConstructor<uint32_t, TestQuantity::High>,
        ConstructorTests::MoveConstructor<uint64_t, TestQuantity::High>,
        ConstructorTests::MoveConstructor<Helper, TestQuantity::High>,

        /// Copy Tests \\\

        CopyTests::CopyAllBufferDataMembers<uint8_t, TestQuantity::None>,
        CopyTests::CopyAllBufferDataMembers<uint16_t, TestQuantity::None>,
        CopyTests::CopyAllBufferDataMembers<uint32_t, TestQuantity::None>,
        CopyTests::CopyAllBufferDataMembers<uint64_t, TestQuantity::None>,
        CopyTests::CopyAllBufferDataMembers<Helper, TestQuantity::None>,
        CopyTests::CopyAllBufferDataMembers<uint8_t, TestQuantity::VeryLow>,
        CopyTests::CopyAllBufferDataMembers<uint16_t, TestQuantity::VeryLow>,
        CopyTests::CopyAllBufferDataMembers<uint32_t, TestQuantity::VeryLow>,
        CopyTests::CopyAllBufferDataMembers<uint64_t, TestQuantity::VeryLow>,
        CopyTests::CopyAllBufferDataMembers<Helper, TestQuantity::VeryLow>,
        CopyTests::CopyAllBufferDataMembers<uint8_t, TestQuantity::High>,
        CopyTests::CopyAllBufferDataMembers<uint16_t, TestQuantity::High>,
        CopyTests::CopyAllBufferDataMembers<uint32_t, TestQuantity::High>,
        CopyTests::CopyAllBufferDataMembers<uint64_t, TestQuantity::High>,
        CopyTests::CopyAllBufferDataMembers<Helper, TestQuantity::High>,

        CopyTests::CopyNonPointerBufferDataMembers<uint8_t, TestQuantity::None>,
        CopyTests::CopyNonPointerBufferDataMembers<uint16_t, TestQuantity::None>,
        CopyTests::CopyNonPointerBufferDataMembers<uint32_t, TestQuantity::None>,
        CopyTests::CopyNonPointerBufferDataMembers<uint64_t, TestQuantity::None>,
        CopyTests::CopyNonPointerBufferDataMembers<Helper, TestQuantity::None>,
        CopyTests::CopyNonPointerBufferDataMembers<uint8_t, TestQuantity::VeryLow>,
        CopyTests::CopyNonPointerBufferDataMembers<uint16_t, TestQuantity::VeryLow>,
        CopyTests::CopyNonPointerBufferDataMembers<uint32_t, TestQuantity::VeryLow>,
        CopyTests::CopyNonPointerBufferDataMembers<uint64_t, TestQuantity::VeryLow>,
        CopyTests::CopyNonPointerBufferDataMembers<Helper, TestQuantity::VeryLow>,
        CopyTests::CopyNonPointerBufferDataMembers<uint8_t, TestQuantity::High>,
        CopyTests::CopyNonPointerBufferDataMembers<uint16_t, TestQuantity::High>,
        CopyTests::CopyNonPointerBufferDataMembers<uint32_t, TestQuantity::High>,
        CopyTests::CopyNonPointerBufferDataMembers<uint64_t, TestQuantity::High>,
        CopyTests::CopyNonPointerBufferDataMembers<Helper, TestQuantity::High>,

        CopyTests::CopyBuffer<uint8_t, TestQuantity::None>,
        CopyTests::CopyBuffer<uint16_t, TestQuantity::None>,
        CopyTests::CopyBuffer<uint32_t, TestQuantity::None>,
        CopyTests::CopyBuffer<uint64_t, TestQuantity::None>,
        CopyTests::CopyBuffer<Helper, TestQuantity::None>,
        CopyTests::CopyBuffer<uint8_t, TestQuantity::VeryLow>,
        CopyTests::CopyBuffer<uint16_t, TestQuantity::VeryLow>,
        CopyTests::CopyBuffer<uint32_t, TestQuantity::VeryLow>,
        CopyTests::CopyBuffer<uint64_t, TestQuantity::VeryLow>,
        CopyTests::CopyBuffer<Helper, TestQuantity::VeryLow>,
        CopyTests::CopyBuffer<uint8_t, TestQuantity::High>,
        CopyTests::CopyBuffer<uint16_t, TestQuantity::High>,
        CopyTests::CopyBuffer<uint32_t, TestQuantity::High>,
        CopyTests::CopyBuffer<uint64_t, TestQuantity::High>,
        CopyTests::CopyBuffer<Helper, TestQuantity::High>,

        CopyTests::CopyAssignment<uint8_t, TestQuantity::None>,
        CopyTests::CopyAssignment<uint16_t, TestQuantity::None>,
        CopyTests::CopyAssignment<uint32_t, TestQuantity::None>,
        CopyTests::CopyAssignment<uint64_t, TestQuantity::None>,
        CopyTests::CopyAssignment<Helper, TestQuantity::None>,
        CopyTests::CopyAssignment<uint8_t, TestQuantity::VeryLow>,
        CopyTests::CopyAssignment<uint16_t, TestQuantity::VeryLow>,
        CopyTests::CopyAssignment<uint32_t, TestQuantity::VeryLow>,
        CopyTests::CopyAssignment<uint64_t, TestQuantity::VeryLow>,
        CopyTests::CopyAssignment<Helper, TestQuantity::VeryLow>,
        CopyTests::CopyAssignment<uint8_t, TestQuantity::High>,
        CopyTests::CopyAssignment<uint16_t, TestQuantity::High>,
        CopyTests::CopyAssignment<uint32_t, TestQuantity::High>,
        CopyTests::CopyAssignment<uint64_t, TestQuantity::High>,
        CopyTests::CopyAssignment<Helper, TestQuantity::High>,

        /// Move Tests \\\

        MoveTests::TransferBuffer<uint8_t, TestQuantity::None>,
        MoveTests::TransferBuffer<uint16_t, TestQuantity::None>,
        MoveTests::TransferBuffer<uint32_t, TestQuantity::None>,
        MoveTests::TransferBuffer<uint64_t, TestQuantity::None>,
        MoveTests::TransferBuffer<Helper, TestQuantity::None>,
        MoveTests::TransferBuffer<uint8_t, TestQuantity::VeryLow>,
        MoveTests::TransferBuffer<uint16_t, TestQuantity::VeryLow>,
        MoveTests::TransferBuffer<uint32_t, TestQuantity::VeryLow>,
        MoveTests::TransferBuffer<uint64_t, TestQuantity::VeryLow>,
        MoveTests::TransferBuffer<Helper, TestQuantity::VeryLow>,
        MoveTests::TransferBuffer<uint8_t, TestQuantity::High>,
        MoveTests::TransferBuffer<uint16_t, TestQuantity::High>,
        MoveTests::TransferBuffer<uint32_t, TestQuantity::High>,
        MoveTests::TransferBuffer<uint64_t, TestQuantity::High>,
        MoveTests::TransferBuffer<Helper, TestQuantity::High>,

        MoveTests::MoveAssignment<uint8_t, TestQuantity::None>,
        MoveTests::MoveAssignment<uint16_t, TestQuantity::None>,
        MoveTests::MoveAssignment<uint32_t, TestQuantity::None>,
        MoveTests::MoveAssignment<uint64_t, TestQuantity::None>,
        MoveTests::MoveAssignment<Helper, TestQuantity::None>,
        MoveTests::MoveAssignment<uint8_t, TestQuantity::VeryLow>,
        MoveTests::MoveAssignment<uint16_t, TestQuantity::VeryLow>,
        MoveTests::MoveAssignment<uint32_t, TestQuantity::VeryLow>,
        MoveTests::MoveAssignment<uint64_t, TestQuantity::VeryLow>,
        MoveTests::MoveAssignment<Helper, TestQuantity::VeryLow>,
        MoveTests::MoveAssignment<uint8_t, TestQuantity::High>,
        MoveTests::MoveAssignment<uint16_t, TestQuantity::High>,
        MoveTests::MoveAssignment<uint32_t, TestQuantity::High>,
        MoveTests::MoveAssignment<uint64_t, TestQuantity::High>,
        MoveTests::MoveAssignment<Helper, TestQuantity::High>,

        /// Subscript Operator Tests \\\

        SubscriptOperatorTests::SubscriptOperator<uint8_t, TestQuantity::None>,
        SubscriptOperatorTests::SubscriptOperator<uint16_t, TestQuantity::None>,
        SubscriptOperatorTests::SubscriptOperator<uint32_t, TestQuantity::None>,
        SubscriptOperatorTests::SubscriptOperator<uint64_t, TestQuantity::None>,
        SubscriptOperatorTests::SubscriptOperator<Helper, TestQuantity::None>,
        SubscriptOperatorTests::SubscriptOperator<uint8_t, TestQuantity::VeryLow>,
        SubscriptOperatorTests::SubscriptOperator<uint16_t, TestQuantity::VeryLow>,
        SubscriptOperatorTests::SubscriptOperator<uint32_t, TestQuantity::VeryLow>,
        SubscriptOperatorTests::SubscriptOperator<uint64_t, TestQuantity::VeryLow>,
        SubscriptOperatorTests::SubscriptOperator<Helper, TestQuantity::VeryLow>,
        SubscriptOperatorTests::SubscriptOperator<uint8_t, TestQuantity::High>,
        SubscriptOperatorTests::SubscriptOperator<uint16_t, TestQuantity::High>,
        SubscriptOperatorTests::SubscriptOperator<uint32_t, TestQuantity::High>,
        SubscriptOperatorTests::SubscriptOperator<uint64_t, TestQuantity::High>,
        SubscriptOperatorTests::SubscriptOperator<Helper, TestQuantity::High>,

        /// Dereference Operator Tests \\\

        DereferenceOperatorTests::DereferenceOperator<uint8_t, TestQuantity::None>,
        DereferenceOperatorTests::DereferenceOperator<uint16_t, TestQuantity::None>,
        DereferenceOperatorTests::DereferenceOperator<uint32_t, TestQuantity::None>,
        DereferenceOperatorTests::DereferenceOperator<uint64_t, TestQuantity::None>,
        DereferenceOperatorTests::DereferenceOperator<Helper, TestQuantity::None>,
        DereferenceOperatorTests::DereferenceOperator<uint8_t, TestQuantity::VeryLow>,
        DereferenceOperatorTests::DereferenceOperator<uint16_t, TestQuantity::VeryLow>,
        DereferenceOperatorTests::DereferenceOperator<uint32_t, TestQuantity::VeryLow>,
        DereferenceOperatorTests::DereferenceOperator<uint64_t, TestQuantity::VeryLow>,
        DereferenceOperatorTests::DereferenceOperator<Helper, TestQuantity::VeryLow>,
        DereferenceOperatorTests::DereferenceOperator<uint8_t, TestQuantity::High>,
        DereferenceOperatorTests::DereferenceOperator<uint16_t, TestQuantity::High>,
        DereferenceOperatorTests::DereferenceOperator<uint32_t, TestQuantity::High>,
        DereferenceOperatorTests::DereferenceOperator<uint64_t, TestQuantity::High>,
        DereferenceOperatorTests::DereferenceOperator<Helper, TestQuantity::High>,

        /// Comparison Tests \\\

        ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::High, TestQuantity::High>,

        ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<Helper, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<Helper, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<Helper, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<Helper, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<Helper, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<Helper, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonPtr<Helper, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonPtr<Helper, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonPtr<Helper, TestQuantity::High, TestQuantity::High>,

        ComparisonTests::Comparison<uint8_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::Comparison<uint8_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint8_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::Comparison<uint8_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::Comparison<uint8_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint8_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::Comparison<uint8_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::Comparison<uint8_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint8_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::Comparison<uint16_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::Comparison<uint16_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint16_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::Comparison<uint16_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::Comparison<uint16_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint16_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::Comparison<uint16_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::Comparison<uint16_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint16_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::Comparison<uint32_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::Comparison<uint32_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint32_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::Comparison<uint32_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::Comparison<uint32_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint32_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::Comparison<uint32_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::Comparison<uint32_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint32_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::Comparison<uint64_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::Comparison<uint64_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint64_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::Comparison<uint64_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::Comparison<uint64_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint64_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::Comparison<uint64_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::Comparison<uint64_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<uint64_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::Comparison<Helper, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::Comparison<Helper, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<Helper, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::Comparison<Helper, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::Comparison<Helper, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<Helper, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::Comparison<Helper, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::Comparison<Helper, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::Comparison<Helper, TestQuantity::High, TestQuantity::High>,

        ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::High, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<Helper, TestQuantity::None, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<Helper, TestQuantity::None, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<Helper, TestQuantity::None, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<Helper, TestQuantity::VeryLow, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<Helper, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<Helper, TestQuantity::VeryLow, TestQuantity::High>,
        ComparisonTests::ComparisonOperator<Helper, TestQuantity::High, TestQuantity::None>,
        ComparisonTests::ComparisonOperator<Helper, TestQuantity::High, TestQuantity::VeryLow>,
        ComparisonTests::ComparisonOperator<Helper, TestQuantity::High, TestQuantity::High>,

        /// Set Write Position Tests \\\

        SetWritePositionTests::SetWritePosition<uint8_t, TestQuantity::None>,
        SetWritePositionTests::SetWritePosition<uint16_t, TestQuantity::None>,
        SetWritePositionTests::SetWritePosition<uint32_t, TestQuantity::None>,
        SetWritePositionTests::SetWritePosition<uint64_t, TestQuantity::None>,
        SetWritePositionTests::SetWritePosition<Helper, TestQuantity::None>,
        SetWritePositionTests::SetWritePosition<uint8_t, TestQuantity::VeryLow>,
        SetWritePositionTests::SetWritePosition<uint16_t, TestQuantity::VeryLow>,
        SetWritePositionTests::SetWritePosition<uint32_t, TestQuantity::VeryLow>,
        SetWritePositionTests::SetWritePosition<uint64_t, TestQuantity::VeryLow>,
        SetWritePositionTests::SetWritePosition<Helper, TestQuantity::VeryLow>,
        SetWritePositionTests::SetWritePosition<uint8_t, TestQuantity::High>,
        SetWritePositionTests::SetWritePosition<uint16_t, TestQuantity::High>,
        SetWritePositionTests::SetWritePosition<uint32_t, TestQuantity::High>,
        SetWritePositionTests::SetWritePosition<uint64_t, TestQuantity::High>,
        SetWritePositionTests::SetWritePosition<Helper, TestQuantity::High>,

        /// Write Tests \\\

        WriteTests::WriteElement<uint8_t, TestQuantity::None, false>,
        WriteTests::WriteElement<uint16_t, TestQuantity::None, false>,
        WriteTests::WriteElement<uint32_t, TestQuantity::None, false>,
        WriteTests::WriteElement<uint64_t, TestQuantity::None, false>,
        WriteTests::WriteElement<Helper, TestQuantity::None, false>,
        WriteTests::WriteElement<uint8_t, TestQuantity::None, true>,
        WriteTests::WriteElement<uint16_t, TestQuantity::None, true>,
        WriteTests::WriteElement<uint32_t, TestQuantity::None, true>,
        WriteTests::WriteElement<uint64_t, TestQuantity::None, true>,
        WriteTests::WriteElement<Helper, TestQuantity::None, true>,
        WriteTests::WriteElement<uint8_t, TestQuantity::VeryLow, false>,
        WriteTests::WriteElement<uint16_t, TestQuantity::VeryLow, false>,
        WriteTests::WriteElement<uint32_t, TestQuantity::VeryLow, false>,
        WriteTests::WriteElement<uint64_t, TestQuantity::VeryLow, false>,
        WriteTests::WriteElement<Helper, TestQuantity::VeryLow, false>,
        WriteTests::WriteElement<uint8_t, TestQuantity::VeryLow, true>,
        WriteTests::WriteElement<uint16_t, TestQuantity::VeryLow, true>,
        WriteTests::WriteElement<uint32_t, TestQuantity::VeryLow, true>,
        WriteTests::WriteElement<uint64_t, TestQuantity::VeryLow, true>,
        WriteTests::WriteElement<Helper, TestQuantity::VeryLow, true>,
        WriteTests::WriteElement<uint8_t, TestQuantity::High, false>,
        WriteTests::WriteElement<uint16_t, TestQuantity::High, false>,
        WriteTests::WriteElement<uint32_t, TestQuantity::High, false>,
        WriteTests::WriteElement<uint64_t, TestQuantity::High, false>,
        WriteTests::WriteElement<Helper, TestQuantity::High, false>,
        WriteTests::WriteElement<uint8_t, TestQuantity::High, true>,
        WriteTests::WriteElement<uint16_t, TestQuantity::High, true>,
        WriteTests::WriteElement<uint32_t, TestQuantity::High, true>,
        WriteTests::WriteElement<uint64_t, TestQuantity::High, true>,
        WriteTests::WriteElement<Helper, TestQuantity::High, true>,

        WriteTests::WritePtrNull<uint8_t, TestQuantity::None, TestQuantity::None>,
        WriteTests::WritePtrNull<uint8_t, TestQuantity::None, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint8_t, TestQuantity::None, TestQuantity::High>,
        WriteTests::WritePtrNull<uint8_t, TestQuantity::VeryLow, TestQuantity::None>,
        WriteTests::WritePtrNull<uint8_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint8_t, TestQuantity::VeryLow, TestQuantity::High>,
        WriteTests::WritePtrNull<uint8_t, TestQuantity::High, TestQuantity::None>,
        WriteTests::WritePtrNull<uint8_t, TestQuantity::High, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint8_t, TestQuantity::High, TestQuantity::High>,
        WriteTests::WritePtrNull<uint16_t, TestQuantity::None, TestQuantity::None>,
        WriteTests::WritePtrNull<uint16_t, TestQuantity::None, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint16_t, TestQuantity::None, TestQuantity::High>,
        WriteTests::WritePtrNull<uint16_t, TestQuantity::VeryLow, TestQuantity::None>,
        WriteTests::WritePtrNull<uint16_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint16_t, TestQuantity::VeryLow, TestQuantity::High>,
        WriteTests::WritePtrNull<uint16_t, TestQuantity::High, TestQuantity::None>,
        WriteTests::WritePtrNull<uint16_t, TestQuantity::High, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint16_t, TestQuantity::High, TestQuantity::High>,
        WriteTests::WritePtrNull<uint32_t, TestQuantity::None, TestQuantity::None>,
        WriteTests::WritePtrNull<uint32_t, TestQuantity::None, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint32_t, TestQuantity::None, TestQuantity::High>,
        WriteTests::WritePtrNull<uint32_t, TestQuantity::VeryLow, TestQuantity::None>,
        WriteTests::WritePtrNull<uint32_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint32_t, TestQuantity::VeryLow, TestQuantity::High>,
        WriteTests::WritePtrNull<uint32_t, TestQuantity::High, TestQuantity::None>,
        WriteTests::WritePtrNull<uint32_t, TestQuantity::High, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint32_t, TestQuantity::High, TestQuantity::High>,
        WriteTests::WritePtrNull<uint64_t, TestQuantity::None, TestQuantity::None>,
        WriteTests::WritePtrNull<uint64_t, TestQuantity::None, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint64_t, TestQuantity::None, TestQuantity::High>,
        WriteTests::WritePtrNull<uint64_t, TestQuantity::VeryLow, TestQuantity::None>,
        WriteTests::WritePtrNull<uint64_t, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint64_t, TestQuantity::VeryLow, TestQuantity::High>,
        WriteTests::WritePtrNull<uint64_t, TestQuantity::High, TestQuantity::None>,
        WriteTests::WritePtrNull<uint64_t, TestQuantity::High, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<uint64_t, TestQuantity::High, TestQuantity::High>,
        WriteTests::WritePtrNull<Helper, TestQuantity::None, TestQuantity::None>,
        WriteTests::WritePtrNull<Helper, TestQuantity::None, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<Helper, TestQuantity::None, TestQuantity::High>,
        WriteTests::WritePtrNull<Helper, TestQuantity::VeryLow, TestQuantity::None>,
        WriteTests::WritePtrNull<Helper, TestQuantity::VeryLow, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<Helper, TestQuantity::VeryLow, TestQuantity::High>,
        WriteTests::WritePtrNull<Helper, TestQuantity::High, TestQuantity::None>,
        WriteTests::WritePtrNull<Helper, TestQuantity::High, TestQuantity::VeryLow>,
        WriteTests::WritePtrNull<Helper, TestQuantity::High, TestQuantity::High>,

        WriteTests::WritePtr<uint8_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WritePtr<uint8_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WritePtr<uint8_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint8_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint8_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WritePtr<uint8_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WritePtr<uint8_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WritePtr<uint8_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WritePtr<uint8_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint8_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint8_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WritePtr<uint8_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WritePtr<uint8_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WritePtr<uint8_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WritePtr<uint8_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint8_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint8_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WritePtr<uint8_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WritePtr<uint16_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WritePtr<uint16_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WritePtr<uint16_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint16_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint16_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WritePtr<uint16_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WritePtr<uint16_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WritePtr<uint16_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WritePtr<uint16_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint16_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint16_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WritePtr<uint16_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WritePtr<uint16_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WritePtr<uint16_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WritePtr<uint16_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint16_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint16_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WritePtr<uint16_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WritePtr<uint32_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WritePtr<uint32_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WritePtr<uint32_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint32_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint32_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WritePtr<uint32_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WritePtr<uint32_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WritePtr<uint32_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WritePtr<uint32_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint32_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint32_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WritePtr<uint32_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WritePtr<uint32_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WritePtr<uint32_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WritePtr<uint32_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint32_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint32_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WritePtr<uint32_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WritePtr<uint64_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WritePtr<uint64_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WritePtr<uint64_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint64_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint64_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WritePtr<uint64_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WritePtr<uint64_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WritePtr<uint64_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WritePtr<uint64_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint64_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint64_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WritePtr<uint64_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WritePtr<uint64_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WritePtr<uint64_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WritePtr<uint64_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<uint64_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<uint64_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WritePtr<uint64_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WritePtr<Helper, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WritePtr<Helper, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WritePtr<Helper, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<Helper, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<Helper, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WritePtr<Helper, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WritePtr<Helper, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WritePtr<Helper, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WritePtr<Helper, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<Helper, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<Helper, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WritePtr<Helper, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WritePtr<Helper, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WritePtr<Helper, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WritePtr<Helper, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WritePtr<Helper, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WritePtr<Helper, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WritePtr<Helper, TestQuantity::High, TestQuantity::High, true>,

        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint8_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint16_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint32_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<uint64_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WriteToWritePosition<Helper, TestQuantity::High, TestQuantity::High, true>,

        WriteTests::WriteToEnd<uint8_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint8_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint16_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint32_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WriteToEnd<uint64_t, TestQuantity::High, TestQuantity::High, true>,
        WriteTests::WriteToEnd<Helper, TestQuantity::None, TestQuantity::None, false>,
        WriteTests::WriteToEnd<Helper, TestQuantity::None, TestQuantity::None, true>,
        WriteTests::WriteToEnd<Helper, TestQuantity::None, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<Helper, TestQuantity::None, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<Helper, TestQuantity::None, TestQuantity::High, false>,
        WriteTests::WriteToEnd<Helper, TestQuantity::None, TestQuantity::High, true>,
        WriteTests::WriteToEnd<Helper, TestQuantity::VeryLow, TestQuantity::None, false>,
        WriteTests::WriteToEnd<Helper, TestQuantity::VeryLow, TestQuantity::None, true>,
        WriteTests::WriteToEnd<Helper, TestQuantity::VeryLow, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<Helper, TestQuantity::VeryLow, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<Helper, TestQuantity::VeryLow, TestQuantity::High, false>,
        WriteTests::WriteToEnd<Helper, TestQuantity::VeryLow, TestQuantity::High, true>,
        WriteTests::WriteToEnd<Helper, TestQuantity::High, TestQuantity::None, false>,
        WriteTests::WriteToEnd<Helper, TestQuantity::High, TestQuantity::None, true>,
        WriteTests::WriteToEnd<Helper, TestQuantity::High, TestQuantity::VeryLow, false>,
        WriteTests::WriteToEnd<Helper, TestQuantity::High, TestQuantity::VeryLow, true>,
        WriteTests::WriteToEnd<Helper, TestQuantity::High, TestQuantity::High, false>,
        WriteTests::WriteToEnd<Helper, TestQuantity::High, TestQuantity::High, true>
    };

    return tests;
}
