#include <CCBufferTests.h>

CC::BufferTests::UTList CC::BufferTests::GetTests( )
{
    static const UTList tests
    {
        /// Allocation Tests \\\

        BufferTests::AllocationTests::Allocate<uint8_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::Allocate<uint16_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::Allocate<uint32_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::Allocate<uint64_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::Allocate<Helper, TestQuantity::Zero>,
        BufferTests::AllocationTests::Allocate<uint8_t, TestQuantity::One>,
        BufferTests::AllocationTests::Allocate<uint16_t, TestQuantity::One>,
        BufferTests::AllocationTests::Allocate<uint32_t, TestQuantity::One>,
        BufferTests::AllocationTests::Allocate<uint64_t, TestQuantity::One>,
        BufferTests::AllocationTests::Allocate<Helper, TestQuantity::One>,
        BufferTests::AllocationTests::Allocate<uint8_t, TestQuantity::Many>,
        BufferTests::AllocationTests::Allocate<uint16_t, TestQuantity::Many>,
        BufferTests::AllocationTests::Allocate<uint32_t, TestQuantity::Many>,
        BufferTests::AllocationTests::Allocate<uint64_t, TestQuantity::Many>,
        BufferTests::AllocationTests::Allocate<Helper, TestQuantity::Many>,

        BufferTests::AllocationTests::AllocFromPtrNull<uint8_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::AllocFromPtrNull<uint16_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::AllocFromPtrNull<uint32_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::AllocFromPtrNull<uint64_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::AllocFromPtrNull<Helper, TestQuantity::Zero>,
        BufferTests::AllocationTests::AllocFromPtrNull<uint8_t, TestQuantity::One>,
        BufferTests::AllocationTests::AllocFromPtrNull<uint16_t, TestQuantity::One>,
        BufferTests::AllocationTests::AllocFromPtrNull<uint32_t, TestQuantity::One>,
        BufferTests::AllocationTests::AllocFromPtrNull<uint64_t, TestQuantity::One>,
        BufferTests::AllocationTests::AllocFromPtrNull<Helper, TestQuantity::One>,
        BufferTests::AllocationTests::AllocFromPtrNull<uint8_t, TestQuantity::Many>,
        BufferTests::AllocationTests::AllocFromPtrNull<uint16_t, TestQuantity::Many>,
        BufferTests::AllocationTests::AllocFromPtrNull<uint32_t, TestQuantity::Many>,
        BufferTests::AllocationTests::AllocFromPtrNull<uint64_t, TestQuantity::Many>,
        BufferTests::AllocationTests::AllocFromPtrNull<Helper, TestQuantity::Many>,

        BufferTests::AllocationTests::AllocFromPtr<uint8_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::AllocFromPtr<uint16_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::AllocFromPtr<uint32_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::AllocFromPtr<uint64_t, TestQuantity::Zero>,
        BufferTests::AllocationTests::AllocFromPtr<Helper, TestQuantity::Zero>,
        BufferTests::AllocationTests::AllocFromPtr<uint8_t, TestQuantity::One>,
        BufferTests::AllocationTests::AllocFromPtr<uint16_t, TestQuantity::One>,
        BufferTests::AllocationTests::AllocFromPtr<uint32_t, TestQuantity::One>,
        BufferTests::AllocationTests::AllocFromPtr<uint64_t, TestQuantity::One>,
        BufferTests::AllocationTests::AllocFromPtr<Helper, TestQuantity::One>,
        BufferTests::AllocationTests::AllocFromPtr<uint8_t, TestQuantity::Many>,
        BufferTests::AllocationTests::AllocFromPtr<uint16_t, TestQuantity::Many>,
        BufferTests::AllocationTests::AllocFromPtr<uint32_t, TestQuantity::Many>,
        BufferTests::AllocationTests::AllocFromPtr<uint64_t, TestQuantity::Many>,
        BufferTests::AllocationTests::AllocFromPtr<Helper, TestQuantity::Many>,

        /// Deallocation Tests \\\

        BufferTests::DeallocationTests::CopyBuffer<uint8_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::CopyBuffer<uint16_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::CopyBuffer<uint32_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::CopyBuffer<uint64_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::CopyBuffer<Helper, TestQuantity::Zero>,
        BufferTests::DeallocationTests::CopyBuffer<uint8_t, TestQuantity::One>,
        BufferTests::DeallocationTests::CopyBuffer<uint16_t, TestQuantity::One>,
        BufferTests::DeallocationTests::CopyBuffer<uint32_t, TestQuantity::One>,
        BufferTests::DeallocationTests::CopyBuffer<uint64_t, TestQuantity::One>,
        BufferTests::DeallocationTests::CopyBuffer<Helper, TestQuantity::One>,
        BufferTests::DeallocationTests::CopyBuffer<uint8_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::CopyBuffer<uint16_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::CopyBuffer<uint32_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::CopyBuffer<uint64_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::CopyBuffer<Helper, TestQuantity::Many>,

        BufferTests::DeallocationTests::TransferBuffer<uint8_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::TransferBuffer<uint16_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::TransferBuffer<uint32_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::TransferBuffer<uint64_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::TransferBuffer<Helper, TestQuantity::Zero>,
        BufferTests::DeallocationTests::TransferBuffer<uint8_t, TestQuantity::One>,
        BufferTests::DeallocationTests::TransferBuffer<uint16_t, TestQuantity::One>,
        BufferTests::DeallocationTests::TransferBuffer<uint32_t, TestQuantity::One>,
        BufferTests::DeallocationTests::TransferBuffer<uint64_t, TestQuantity::One>,
        BufferTests::DeallocationTests::TransferBuffer<Helper, TestQuantity::One>,
        BufferTests::DeallocationTests::TransferBuffer<uint8_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::TransferBuffer<uint16_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::TransferBuffer<uint32_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::TransferBuffer<uint64_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::TransferBuffer<Helper, TestQuantity::Many>,

        BufferTests::DeallocationTests::Destructor<uint8_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::Destructor<uint16_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::Destructor<uint32_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::Destructor<uint64_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::Destructor<Helper, TestQuantity::Zero>,
        BufferTests::DeallocationTests::Destructor<uint8_t, TestQuantity::One>,
        BufferTests::DeallocationTests::Destructor<uint16_t, TestQuantity::One>,
        BufferTests::DeallocationTests::Destructor<uint32_t, TestQuantity::One>,
        BufferTests::DeallocationTests::Destructor<uint64_t, TestQuantity::One>,
        BufferTests::DeallocationTests::Destructor<Helper, TestQuantity::One>,
        BufferTests::DeallocationTests::Destructor<uint8_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::Destructor<uint16_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::Destructor<uint32_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::Destructor<uint64_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::Destructor<Helper, TestQuantity::Many>,

        BufferTests::DeallocationTests::Free<uint8_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::Free<uint16_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::Free<uint32_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::Free<uint64_t, TestQuantity::Zero>,
        BufferTests::DeallocationTests::Free<Helper, TestQuantity::Zero>,
        BufferTests::DeallocationTests::Free<uint8_t, TestQuantity::One>,
        BufferTests::DeallocationTests::Free<uint16_t, TestQuantity::One>,
        BufferTests::DeallocationTests::Free<uint32_t, TestQuantity::One>,
        BufferTests::DeallocationTests::Free<uint64_t, TestQuantity::One>,
        BufferTests::DeallocationTests::Free<Helper, TestQuantity::One>,
        BufferTests::DeallocationTests::Free<uint8_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::Free<uint16_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::Free<uint32_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::Free<uint64_t, TestQuantity::Many>,
        BufferTests::DeallocationTests::Free<Helper, TestQuantity::Many>,

        /// Constructor Tests \\\

        BufferTests::ConstructorTests::DefaultConstructor<uint8_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::DefaultConstructor<uint16_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::DefaultConstructor<uint32_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::DefaultConstructor<uint64_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::DefaultConstructor<Helper, TestQuantity::Zero>,
        BufferTests::ConstructorTests::DefaultConstructor<uint8_t, TestQuantity::One>,
        BufferTests::ConstructorTests::DefaultConstructor<uint16_t, TestQuantity::One>,
        BufferTests::ConstructorTests::DefaultConstructor<uint32_t, TestQuantity::One>,
        BufferTests::ConstructorTests::DefaultConstructor<uint64_t, TestQuantity::One>,
        BufferTests::ConstructorTests::DefaultConstructor<Helper, TestQuantity::One>,
        BufferTests::ConstructorTests::DefaultConstructor<uint8_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::DefaultConstructor<uint16_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::DefaultConstructor<uint32_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::DefaultConstructor<uint64_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::DefaultConstructor<Helper, TestQuantity::Many>,

        BufferTests::ConstructorTests::LengthConstructor<uint8_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::LengthConstructor<uint16_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::LengthConstructor<uint32_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::LengthConstructor<uint64_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::LengthConstructor<Helper, TestQuantity::Zero>,
        BufferTests::ConstructorTests::LengthConstructor<uint8_t, TestQuantity::One>,
        BufferTests::ConstructorTests::LengthConstructor<uint16_t, TestQuantity::One>,
        BufferTests::ConstructorTests::LengthConstructor<uint32_t, TestQuantity::One>,
        BufferTests::ConstructorTests::LengthConstructor<uint64_t, TestQuantity::One>,
        BufferTests::ConstructorTests::LengthConstructor<Helper, TestQuantity::One>,
        BufferTests::ConstructorTests::LengthConstructor<uint8_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::LengthConstructor<uint16_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::LengthConstructor<uint32_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::LengthConstructor<uint64_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::LengthConstructor<Helper, TestQuantity::Many>,

        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint8_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint16_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint32_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint64_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<Helper, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint8_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint16_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint32_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint64_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<Helper, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint8_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint16_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint32_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<uint64_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerCopyConstructorNull<Helper, TestQuantity::Many>,

        BufferTests::ConstructorTests::PointerCopyConstructor<uint8_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerCopyConstructor<uint16_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerCopyConstructor<uint32_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerCopyConstructor<uint64_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerCopyConstructor<Helper, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerCopyConstructor<uint8_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerCopyConstructor<uint16_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerCopyConstructor<uint32_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerCopyConstructor<uint64_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerCopyConstructor<Helper, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerCopyConstructor<uint8_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerCopyConstructor<uint16_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerCopyConstructor<uint32_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerCopyConstructor<uint64_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerCopyConstructor<Helper, TestQuantity::Many>,

        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint8_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint16_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint32_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint64_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<Helper, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint8_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint16_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint32_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint64_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<Helper, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint8_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint16_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint32_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<uint64_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerMoveConstructorNull<Helper, TestQuantity::Many>,

        BufferTests::ConstructorTests::PointerMoveConstructor<uint8_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerMoveConstructor<uint16_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerMoveConstructor<uint32_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerMoveConstructor<uint64_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerMoveConstructor<Helper, TestQuantity::Zero>,
        BufferTests::ConstructorTests::PointerMoveConstructor<uint8_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerMoveConstructor<uint16_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerMoveConstructor<uint32_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerMoveConstructor<uint64_t, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerMoveConstructor<Helper, TestQuantity::One>,
        BufferTests::ConstructorTests::PointerMoveConstructor<uint8_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerMoveConstructor<uint16_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerMoveConstructor<uint32_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerMoveConstructor<uint64_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::PointerMoveConstructor<Helper, TestQuantity::Many>,

        BufferTests::ConstructorTests::CopyConstructor<uint8_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::CopyConstructor<uint16_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::CopyConstructor<uint32_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::CopyConstructor<uint64_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::CopyConstructor<Helper, TestQuantity::Zero>,
        BufferTests::ConstructorTests::CopyConstructor<uint8_t, TestQuantity::One>,
        BufferTests::ConstructorTests::CopyConstructor<uint16_t, TestQuantity::One>,
        BufferTests::ConstructorTests::CopyConstructor<uint32_t, TestQuantity::One>,
        BufferTests::ConstructorTests::CopyConstructor<uint64_t, TestQuantity::One>,
        BufferTests::ConstructorTests::CopyConstructor<Helper, TestQuantity::One>,
        BufferTests::ConstructorTests::CopyConstructor<uint8_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::CopyConstructor<uint16_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::CopyConstructor<uint32_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::CopyConstructor<uint64_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::CopyConstructor<Helper, TestQuantity::Many>,

        BufferTests::ConstructorTests::MoveConstructor<uint8_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::MoveConstructor<uint16_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::MoveConstructor<uint32_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::MoveConstructor<uint64_t, TestQuantity::Zero>,
        BufferTests::ConstructorTests::MoveConstructor<Helper, TestQuantity::Zero>,
        BufferTests::ConstructorTests::MoveConstructor<uint8_t, TestQuantity::One>,
        BufferTests::ConstructorTests::MoveConstructor<uint16_t, TestQuantity::One>,
        BufferTests::ConstructorTests::MoveConstructor<uint32_t, TestQuantity::One>,
        BufferTests::ConstructorTests::MoveConstructor<uint64_t, TestQuantity::One>,
        BufferTests::ConstructorTests::MoveConstructor<Helper, TestQuantity::One>,
        BufferTests::ConstructorTests::MoveConstructor<uint8_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::MoveConstructor<uint16_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::MoveConstructor<uint32_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::MoveConstructor<uint64_t, TestQuantity::Many>,
        BufferTests::ConstructorTests::MoveConstructor<Helper, TestQuantity::Many>,

        /// Copy Tests \\\

        BufferTests::CopyTests::CopyAllBufferDataMembers<uint8_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<uint16_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<uint32_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<uint64_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<Helper, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<uint8_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<uint16_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<uint32_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<uint64_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<Helper, TestQuantity::One>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<uint8_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<uint16_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<uint32_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<uint64_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyAllBufferDataMembers<Helper, TestQuantity::Many>,

        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint8_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint16_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint32_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint64_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<Helper, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint8_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint16_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint32_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint64_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<Helper, TestQuantity::One>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint8_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint16_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint32_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<uint64_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyNonPointerBufferDataMembers<Helper, TestQuantity::Many>,

        BufferTests::CopyTests::CopyBuffer<uint8_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyBuffer<uint16_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyBuffer<uint32_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyBuffer<uint64_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyBuffer<Helper, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyBuffer<uint8_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyBuffer<uint16_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyBuffer<uint32_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyBuffer<uint64_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyBuffer<Helper, TestQuantity::One>,
        BufferTests::CopyTests::CopyBuffer<uint8_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyBuffer<uint16_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyBuffer<uint32_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyBuffer<uint64_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyBuffer<Helper, TestQuantity::Many>,

        BufferTests::CopyTests::CopyAssignment<uint8_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyAssignment<uint16_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyAssignment<uint32_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyAssignment<uint64_t, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyAssignment<Helper, TestQuantity::Zero>,
        BufferTests::CopyTests::CopyAssignment<uint8_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyAssignment<uint16_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyAssignment<uint32_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyAssignment<uint64_t, TestQuantity::One>,
        BufferTests::CopyTests::CopyAssignment<Helper, TestQuantity::One>,
        BufferTests::CopyTests::CopyAssignment<uint8_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyAssignment<uint16_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyAssignment<uint32_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyAssignment<uint64_t, TestQuantity::Many>,
        BufferTests::CopyTests::CopyAssignment<Helper, TestQuantity::Many>,

        /// Move Tests \\\

        BufferTests::MoveTests::TransferBuffer<uint8_t, TestQuantity::Zero>,
        BufferTests::MoveTests::TransferBuffer<uint16_t, TestQuantity::Zero>,
        BufferTests::MoveTests::TransferBuffer<uint32_t, TestQuantity::Zero>,
        BufferTests::MoveTests::TransferBuffer<uint64_t, TestQuantity::Zero>,
        BufferTests::MoveTests::TransferBuffer<Helper, TestQuantity::Zero>,
        BufferTests::MoveTests::TransferBuffer<uint8_t, TestQuantity::One>,
        BufferTests::MoveTests::TransferBuffer<uint16_t, TestQuantity::One>,
        BufferTests::MoveTests::TransferBuffer<uint32_t, TestQuantity::One>,
        BufferTests::MoveTests::TransferBuffer<uint64_t, TestQuantity::One>,
        BufferTests::MoveTests::TransferBuffer<Helper, TestQuantity::One>,
        BufferTests::MoveTests::TransferBuffer<uint8_t, TestQuantity::Many>,
        BufferTests::MoveTests::TransferBuffer<uint16_t, TestQuantity::Many>,
        BufferTests::MoveTests::TransferBuffer<uint32_t, TestQuantity::Many>,
        BufferTests::MoveTests::TransferBuffer<uint64_t, TestQuantity::Many>,
        BufferTests::MoveTests::TransferBuffer<Helper, TestQuantity::Many>,

        BufferTests::MoveTests::MoveAssignment<uint8_t, TestQuantity::Zero>,
        BufferTests::MoveTests::MoveAssignment<uint16_t, TestQuantity::Zero>,
        BufferTests::MoveTests::MoveAssignment<uint32_t, TestQuantity::Zero>,
        BufferTests::MoveTests::MoveAssignment<uint64_t, TestQuantity::Zero>,
        BufferTests::MoveTests::MoveAssignment<Helper, TestQuantity::Zero>,
        BufferTests::MoveTests::MoveAssignment<uint8_t, TestQuantity::One>,
        BufferTests::MoveTests::MoveAssignment<uint16_t, TestQuantity::One>,
        BufferTests::MoveTests::MoveAssignment<uint32_t, TestQuantity::One>,
        BufferTests::MoveTests::MoveAssignment<uint64_t, TestQuantity::One>,
        BufferTests::MoveTests::MoveAssignment<Helper, TestQuantity::One>,
        BufferTests::MoveTests::MoveAssignment<uint8_t, TestQuantity::Many>,
        BufferTests::MoveTests::MoveAssignment<uint16_t, TestQuantity::Many>,
        BufferTests::MoveTests::MoveAssignment<uint32_t, TestQuantity::Many>,
        BufferTests::MoveTests::MoveAssignment<uint64_t, TestQuantity::Many>,
        BufferTests::MoveTests::MoveAssignment<Helper, TestQuantity::Many>,

        /// Subscript Operator Tests \\\

        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint8_t, TestQuantity::Zero>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint16_t, TestQuantity::Zero>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint32_t, TestQuantity::Zero>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint64_t, TestQuantity::Zero>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<Helper, TestQuantity::Zero>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint8_t, TestQuantity::One>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint16_t, TestQuantity::One>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint32_t, TestQuantity::One>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint64_t, TestQuantity::One>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<Helper, TestQuantity::One>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint8_t, TestQuantity::Many>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint16_t, TestQuantity::Many>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint32_t, TestQuantity::Many>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<uint64_t, TestQuantity::Many>,
        BufferTests::SubscriptOperatorTests::SubscriptOperator<Helper, TestQuantity::Many>,

        /// Dereference Operator Tests \\\

        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint8_t, TestQuantity::Zero>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint16_t, TestQuantity::Zero>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint32_t, TestQuantity::Zero>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint64_t, TestQuantity::Zero>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<Helper, TestQuantity::Zero>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint8_t, TestQuantity::One>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint16_t, TestQuantity::One>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint32_t, TestQuantity::One>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint64_t, TestQuantity::One>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<Helper, TestQuantity::One>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint8_t, TestQuantity::Many>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint16_t, TestQuantity::Many>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint32_t, TestQuantity::Many>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<uint64_t, TestQuantity::Many>,
        BufferTests::DereferenceOperatorTests::DereferenceOperator<Helper, TestQuantity::Many>,

        /// Comparison Tests \\\

        BufferTests::ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint8_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint16_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint32_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<uint64_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtrNull<Helper, TestQuantity::Many, TestQuantity::Many>,

        BufferTests::ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint8_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint16_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint32_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<uint64_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<Helper, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<Helper, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<Helper, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<Helper, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<Helper, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<Helper, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonPtr<Helper, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonPtr<Helper, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonPtr<Helper, TestQuantity::Many, TestQuantity::Many>,

        BufferTests::ComparisonTests::Comparison<uint8_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint8_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint8_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<uint8_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint8_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint8_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<uint8_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint8_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint8_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<uint16_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint16_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint16_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<uint16_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint16_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint16_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<uint16_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint16_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint16_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<uint32_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint32_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint32_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<uint32_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint32_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint32_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<uint32_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint32_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint32_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<uint64_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint64_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint64_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<uint64_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint64_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint64_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<uint64_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<uint64_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<uint64_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<Helper, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<Helper, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<Helper, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<Helper, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<Helper, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<Helper, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::Comparison<Helper, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::Comparison<Helper, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::Comparison<Helper, TestQuantity::Many, TestQuantity::Many>,

        BufferTests::ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint8_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint16_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint32_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<uint64_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<Helper, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<Helper, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<Helper, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<Helper, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<Helper, TestQuantity::One, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<Helper, TestQuantity::One, TestQuantity::Many>,
        BufferTests::ComparisonTests::ComparisonOperator<Helper, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::ComparisonTests::ComparisonOperator<Helper, TestQuantity::Many, TestQuantity::One>,
        BufferTests::ComparisonTests::ComparisonOperator<Helper, TestQuantity::Many, TestQuantity::Many>,

        /// Set Write Position Tests \\\

        BufferTests::SetWritePositionTests::SetWritePosition<uint8_t, TestQuantity::Zero>,
        BufferTests::SetWritePositionTests::SetWritePosition<uint16_t, TestQuantity::Zero>,
        BufferTests::SetWritePositionTests::SetWritePosition<uint32_t, TestQuantity::Zero>,
        BufferTests::SetWritePositionTests::SetWritePosition<uint64_t, TestQuantity::Zero>,
        BufferTests::SetWritePositionTests::SetWritePosition<Helper, TestQuantity::Zero>,
        BufferTests::SetWritePositionTests::SetWritePosition<uint8_t, TestQuantity::One>,
        BufferTests::SetWritePositionTests::SetWritePosition<uint16_t, TestQuantity::One>,
        BufferTests::SetWritePositionTests::SetWritePosition<uint32_t, TestQuantity::One>,
        BufferTests::SetWritePositionTests::SetWritePosition<uint64_t, TestQuantity::One>,
        BufferTests::SetWritePositionTests::SetWritePosition<Helper, TestQuantity::One>,
        BufferTests::SetWritePositionTests::SetWritePosition<uint8_t, TestQuantity::Many>,
        BufferTests::SetWritePositionTests::SetWritePosition<uint16_t, TestQuantity::Many>,
        BufferTests::SetWritePositionTests::SetWritePosition<uint32_t, TestQuantity::Many>,
        BufferTests::SetWritePositionTests::SetWritePosition<uint64_t, TestQuantity::Many>,
        BufferTests::SetWritePositionTests::SetWritePosition<Helper, TestQuantity::Many>,

        /// Write Tests \\\

        BufferTests::WriteTests::WriteElement<uint8_t, TestQuantity::Zero, false>,
        BufferTests::WriteTests::WriteElement<uint16_t, TestQuantity::Zero, false>,
        BufferTests::WriteTests::WriteElement<uint32_t, TestQuantity::Zero, false>,
        BufferTests::WriteTests::WriteElement<uint64_t, TestQuantity::Zero, false>,
        BufferTests::WriteTests::WriteElement<Helper, TestQuantity::Zero, false>,
        BufferTests::WriteTests::WriteElement<uint8_t, TestQuantity::Zero, true>,
        BufferTests::WriteTests::WriteElement<uint16_t, TestQuantity::Zero, true>,
        BufferTests::WriteTests::WriteElement<uint32_t, TestQuantity::Zero, true>,
        BufferTests::WriteTests::WriteElement<uint64_t, TestQuantity::Zero, true>,
        BufferTests::WriteTests::WriteElement<Helper, TestQuantity::Zero, true>,
        BufferTests::WriteTests::WriteElement<uint8_t, TestQuantity::One, false>,
        BufferTests::WriteTests::WriteElement<uint16_t, TestQuantity::One, false>,
        BufferTests::WriteTests::WriteElement<uint32_t, TestQuantity::One, false>,
        BufferTests::WriteTests::WriteElement<uint64_t, TestQuantity::One, false>,
        BufferTests::WriteTests::WriteElement<Helper, TestQuantity::One, false>,
        BufferTests::WriteTests::WriteElement<uint8_t, TestQuantity::One, true>,
        BufferTests::WriteTests::WriteElement<uint16_t, TestQuantity::One, true>,
        BufferTests::WriteTests::WriteElement<uint32_t, TestQuantity::One, true>,
        BufferTests::WriteTests::WriteElement<uint64_t, TestQuantity::One, true>,
        BufferTests::WriteTests::WriteElement<Helper, TestQuantity::One, true>,
        BufferTests::WriteTests::WriteElement<uint8_t, TestQuantity::Many, false>,
        BufferTests::WriteTests::WriteElement<uint16_t, TestQuantity::Many, false>,
        BufferTests::WriteTests::WriteElement<uint32_t, TestQuantity::Many, false>,
        BufferTests::WriteTests::WriteElement<uint64_t, TestQuantity::Many, false>,
        BufferTests::WriteTests::WriteElement<Helper, TestQuantity::Many, false>,
        BufferTests::WriteTests::WriteElement<uint8_t, TestQuantity::Many, true>,
        BufferTests::WriteTests::WriteElement<uint16_t, TestQuantity::Many, true>,
        BufferTests::WriteTests::WriteElement<uint32_t, TestQuantity::Many, true>,
        BufferTests::WriteTests::WriteElement<uint64_t, TestQuantity::Many, true>,
        BufferTests::WriteTests::WriteElement<Helper, TestQuantity::Many, true>,

        BufferTests::WriteTests::WritePtrNull<uint8_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint8_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint8_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<uint8_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint8_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint8_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<uint8_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint8_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint8_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<uint16_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint16_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint16_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<uint16_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint16_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint16_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<uint16_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint16_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint16_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<uint32_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint32_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint32_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<uint32_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint32_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint32_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<uint32_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint32_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint32_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<uint64_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint64_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint64_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<uint64_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint64_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint64_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<uint64_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<uint64_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<uint64_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<Helper, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<Helper, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<Helper, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<Helper, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<Helper, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<Helper, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtrNull<Helper, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtrNull<Helper, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WritePtrNull<Helper, TestQuantity::Many, TestQuantity::Many>,

        BufferTests::WriteTests::WritePtr<uint8_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint8_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint8_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<uint8_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint8_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint8_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<uint8_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint8_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint8_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<uint16_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint16_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint16_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<uint16_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint16_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint16_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<uint16_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint16_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint16_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<uint32_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint32_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint32_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<uint32_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint32_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint32_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<uint32_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint32_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint32_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<uint64_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint64_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint64_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<uint64_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint64_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint64_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<uint64_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<uint64_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<uint64_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<Helper, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<Helper, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<Helper, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<Helper, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<Helper, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<Helper, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WritePtr<Helper, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WritePtr<Helper, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WritePtr<Helper, TestQuantity::Many, TestQuantity::Many>,

        BufferTests::WriteTests::WriteToWritePosition<uint8_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint8_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint8_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<uint8_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint8_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint8_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<uint8_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint8_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint8_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<uint16_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint16_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint16_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<uint16_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint16_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint16_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<uint16_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint16_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint16_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<uint32_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint32_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint32_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<uint32_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint32_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint32_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<uint32_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint32_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint32_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<uint64_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint64_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint64_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<uint64_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint64_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint64_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<uint64_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<uint64_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<uint64_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<Helper, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<Helper, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<Helper, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<Helper, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<Helper, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<Helper, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToWritePosition<Helper, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToWritePosition<Helper, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WriteToWritePosition<Helper, TestQuantity::Many, TestQuantity::Many>,

        BufferTests::WriteTests::WriteToEnd<uint8_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint8_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint8_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<uint8_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint8_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint8_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<uint8_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint8_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint8_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<uint16_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint16_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint16_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<uint16_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint16_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint16_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<uint16_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint16_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint16_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<uint32_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint32_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint32_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<uint32_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint32_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint32_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<uint32_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint32_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint32_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<uint64_t, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint64_t, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint64_t, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<uint64_t, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint64_t, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint64_t, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<uint64_t, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<uint64_t, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<uint64_t, TestQuantity::Many, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<Helper, TestQuantity::Zero, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<Helper, TestQuantity::Zero, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<Helper, TestQuantity::Zero, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<Helper, TestQuantity::One, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<Helper, TestQuantity::One, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<Helper, TestQuantity::One, TestQuantity::Many>,
        BufferTests::WriteTests::WriteToEnd<Helper, TestQuantity::Many, TestQuantity::Zero>,
        BufferTests::WriteTests::WriteToEnd<Helper, TestQuantity::Many, TestQuantity::One>,
        BufferTests::WriteTests::WriteToEnd<Helper, TestQuantity::Many, TestQuantity::Many>
    };

    return tests;
}
