#include <CCDynamicBufferTests.h>


namespace CC
{
    CC::DynamicBufferTests::UTList CC::DynamicBufferTests::GetTests()
    {
    #pragma warning(suppress : 6262)
        static const UTList tests
        {
            WriteTests::WriteElement<uint8_t, TQ::None, false>,
            WriteTests::WriteElement<uint8_t, TQ::None, true>,
            WriteTests::WriteElement<uint8_t, TQ::VeryLow, false>,
            WriteTests::WriteElement<uint8_t, TQ::VeryLow, true>,
            WriteTests::WriteElement<uint8_t, TQ::Low, false>,
            WriteTests::WriteElement<uint8_t, TQ::Low, true>,
            WriteTests::WriteElement<uint8_t, TQ::Mid, false>,
            WriteTests::WriteElement<uint8_t, TQ::Mid, true>,
            WriteTests::WriteElement<uint8_t, TQ::High, false>,
            WriteTests::WriteElement<uint8_t, TQ::High, true>,
            WriteTests::WriteElement<uint16_t, TQ::None, false>,
            WriteTests::WriteElement<uint16_t, TQ::None, true>,
            WriteTests::WriteElement<uint16_t, TQ::VeryLow, false>,
            WriteTests::WriteElement<uint16_t, TQ::VeryLow, true>,
            WriteTests::WriteElement<uint16_t, TQ::Low, false>,
            WriteTests::WriteElement<uint16_t, TQ::Low, true>,
            WriteTests::WriteElement<uint16_t, TQ::Mid, false>,
            WriteTests::WriteElement<uint16_t, TQ::Mid, true>,
            WriteTests::WriteElement<uint16_t, TQ::High, false>,
            WriteTests::WriteElement<uint16_t, TQ::High, true>,
            WriteTests::WriteElement<uint32_t, TQ::None, false>,
            WriteTests::WriteElement<uint32_t, TQ::None, true>,
            WriteTests::WriteElement<uint32_t, TQ::VeryLow, false>,
            WriteTests::WriteElement<uint32_t, TQ::VeryLow, true>,
            WriteTests::WriteElement<uint32_t, TQ::Low, false>,
            WriteTests::WriteElement<uint32_t, TQ::Low, true>,
            WriteTests::WriteElement<uint32_t, TQ::Mid, false>,
            WriteTests::WriteElement<uint32_t, TQ::Mid, true>,
            WriteTests::WriteElement<uint32_t, TQ::High, false>,
            WriteTests::WriteElement<uint32_t, TQ::High, true>,
            WriteTests::WriteElement<uint64_t, TQ::None, false>,
            WriteTests::WriteElement<uint64_t, TQ::None, true>,
            WriteTests::WriteElement<uint64_t, TQ::VeryLow, false>,
            WriteTests::WriteElement<uint64_t, TQ::VeryLow, true>,
            WriteTests::WriteElement<uint64_t, TQ::Low, false>,
            WriteTests::WriteElement<uint64_t, TQ::Low, true>,
            WriteTests::WriteElement<uint64_t, TQ::Mid, false>,
            WriteTests::WriteElement<uint64_t, TQ::Mid, true>,
            WriteTests::WriteElement<uint64_t, TQ::High, false>,
            WriteTests::WriteElement<uint64_t, TQ::High, true>,
            WriteTests::WriteElement<Helper, TQ::None, false>,
            WriteTests::WriteElement<Helper, TQ::None, true>,
            WriteTests::WriteElement<Helper, TQ::VeryLow, false>,
            WriteTests::WriteElement<Helper, TQ::VeryLow, true>,
            WriteTests::WriteElement<Helper, TQ::Low, false>,
            WriteTests::WriteElement<Helper, TQ::Low, true>,
            WriteTests::WriteElement<Helper, TQ::Mid, false>,
            WriteTests::WriteElement<Helper, TQ::Mid, true>,
            WriteTests::WriteElement<Helper, TQ::High, false>,
            WriteTests::WriteElement<Helper, TQ::High, true>,

            WriteTests::WritePtrNull<uint8_t, TQ::None, TQ::None>,
            WriteTests::WritePtrNull<uint8_t, TQ::None, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint8_t, TQ::None, TQ::Low>,
            WriteTests::WritePtrNull<uint8_t, TQ::None, TQ::Mid>,
            WriteTests::WritePtrNull<uint8_t, TQ::None, TQ::High>,
            WriteTests::WritePtrNull<uint8_t, TQ::VeryLow, TQ::None>,
            WriteTests::WritePtrNull<uint8_t, TQ::VeryLow, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint8_t, TQ::VeryLow, TQ::Low>,
            WriteTests::WritePtrNull<uint8_t, TQ::VeryLow, TQ::Mid>,
            WriteTests::WritePtrNull<uint8_t, TQ::VeryLow, TQ::High>,
            WriteTests::WritePtrNull<uint8_t, TQ::Low, TQ::None>,
            WriteTests::WritePtrNull<uint8_t, TQ::Low, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint8_t, TQ::Low, TQ::Low>,
            WriteTests::WritePtrNull<uint8_t, TQ::Low, TQ::Mid>,
            WriteTests::WritePtrNull<uint8_t, TQ::Low, TQ::High>,
            WriteTests::WritePtrNull<uint8_t, TQ::Mid, TQ::None>,
            WriteTests::WritePtrNull<uint8_t, TQ::Mid, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint8_t, TQ::Mid, TQ::Low>,
            WriteTests::WritePtrNull<uint8_t, TQ::Mid, TQ::Mid>,
            WriteTests::WritePtrNull<uint8_t, TQ::Mid, TQ::High>,
            WriteTests::WritePtrNull<uint8_t, TQ::High, TQ::None>,
            WriteTests::WritePtrNull<uint8_t, TQ::High, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint8_t, TQ::High, TQ::Low>,
            WriteTests::WritePtrNull<uint8_t, TQ::High, TQ::Mid>,
            WriteTests::WritePtrNull<uint8_t, TQ::High, TQ::High>,
            WriteTests::WritePtrNull<uint16_t, TQ::None, TQ::None>,
            WriteTests::WritePtrNull<uint16_t, TQ::None, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint16_t, TQ::None, TQ::Low>,
            WriteTests::WritePtrNull<uint16_t, TQ::None, TQ::Mid>,
            WriteTests::WritePtrNull<uint16_t, TQ::None, TQ::High>,
            WriteTests::WritePtrNull<uint16_t, TQ::VeryLow, TQ::None>,
            WriteTests::WritePtrNull<uint16_t, TQ::VeryLow, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint16_t, TQ::VeryLow, TQ::Low>,
            WriteTests::WritePtrNull<uint16_t, TQ::VeryLow, TQ::Mid>,
            WriteTests::WritePtrNull<uint16_t, TQ::VeryLow, TQ::High>,
            WriteTests::WritePtrNull<uint16_t, TQ::Low, TQ::None>,
            WriteTests::WritePtrNull<uint16_t, TQ::Low, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint16_t, TQ::Low, TQ::Low>,
            WriteTests::WritePtrNull<uint16_t, TQ::Low, TQ::Mid>,
            WriteTests::WritePtrNull<uint16_t, TQ::Low, TQ::High>,
            WriteTests::WritePtrNull<uint16_t, TQ::Mid, TQ::None>,
            WriteTests::WritePtrNull<uint16_t, TQ::Mid, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint16_t, TQ::Mid, TQ::Low>,
            WriteTests::WritePtrNull<uint16_t, TQ::Mid, TQ::Mid>,
            WriteTests::WritePtrNull<uint16_t, TQ::Mid, TQ::High>,
            WriteTests::WritePtrNull<uint16_t, TQ::High, TQ::None>,
            WriteTests::WritePtrNull<uint16_t, TQ::High, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint16_t, TQ::High, TQ::Low>,
            WriteTests::WritePtrNull<uint16_t, TQ::High, TQ::Mid>,
            WriteTests::WritePtrNull<uint16_t, TQ::High, TQ::High>,
            WriteTests::WritePtrNull<uint32_t, TQ::None, TQ::None>,
            WriteTests::WritePtrNull<uint32_t, TQ::None, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint32_t, TQ::None, TQ::Low>,
            WriteTests::WritePtrNull<uint32_t, TQ::None, TQ::Mid>,
            WriteTests::WritePtrNull<uint32_t, TQ::None, TQ::High>,
            WriteTests::WritePtrNull<uint32_t, TQ::VeryLow, TQ::None>,
            WriteTests::WritePtrNull<uint32_t, TQ::VeryLow, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint32_t, TQ::VeryLow, TQ::Low>,
            WriteTests::WritePtrNull<uint32_t, TQ::VeryLow, TQ::Mid>,
            WriteTests::WritePtrNull<uint32_t, TQ::VeryLow, TQ::High>,
            WriteTests::WritePtrNull<uint32_t, TQ::Low, TQ::None>,
            WriteTests::WritePtrNull<uint32_t, TQ::Low, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint32_t, TQ::Low, TQ::Low>,
            WriteTests::WritePtrNull<uint32_t, TQ::Low, TQ::Mid>,
            WriteTests::WritePtrNull<uint32_t, TQ::Low, TQ::High>,
            WriteTests::WritePtrNull<uint32_t, TQ::Mid, TQ::None>,
            WriteTests::WritePtrNull<uint32_t, TQ::Mid, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint32_t, TQ::Mid, TQ::Low>,
            WriteTests::WritePtrNull<uint32_t, TQ::Mid, TQ::Mid>,
            WriteTests::WritePtrNull<uint32_t, TQ::Mid, TQ::High>,
            WriteTests::WritePtrNull<uint32_t, TQ::High, TQ::None>,
            WriteTests::WritePtrNull<uint32_t, TQ::High, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint32_t, TQ::High, TQ::Low>,
            WriteTests::WritePtrNull<uint32_t, TQ::High, TQ::Mid>,
            WriteTests::WritePtrNull<uint32_t, TQ::High, TQ::High>,
            WriteTests::WritePtrNull<uint64_t, TQ::None, TQ::None>,
            WriteTests::WritePtrNull<uint64_t, TQ::None, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint64_t, TQ::None, TQ::Low>,
            WriteTests::WritePtrNull<uint64_t, TQ::None, TQ::Mid>,
            WriteTests::WritePtrNull<uint64_t, TQ::None, TQ::High>,
            WriteTests::WritePtrNull<uint64_t, TQ::VeryLow, TQ::None>,
            WriteTests::WritePtrNull<uint64_t, TQ::VeryLow, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint64_t, TQ::VeryLow, TQ::Low>,
            WriteTests::WritePtrNull<uint64_t, TQ::VeryLow, TQ::Mid>,
            WriteTests::WritePtrNull<uint64_t, TQ::VeryLow, TQ::High>,
            WriteTests::WritePtrNull<uint64_t, TQ::Low, TQ::None>,
            WriteTests::WritePtrNull<uint64_t, TQ::Low, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint64_t, TQ::Low, TQ::Low>,
            WriteTests::WritePtrNull<uint64_t, TQ::Low, TQ::Mid>,
            WriteTests::WritePtrNull<uint64_t, TQ::Low, TQ::High>,
            WriteTests::WritePtrNull<uint64_t, TQ::Mid, TQ::None>,
            WriteTests::WritePtrNull<uint64_t, TQ::Mid, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint64_t, TQ::Mid, TQ::Low>,
            WriteTests::WritePtrNull<uint64_t, TQ::Mid, TQ::Mid>,
            WriteTests::WritePtrNull<uint64_t, TQ::Mid, TQ::High>,
            WriteTests::WritePtrNull<uint64_t, TQ::High, TQ::None>,
            WriteTests::WritePtrNull<uint64_t, TQ::High, TQ::VeryLow>,
            WriteTests::WritePtrNull<uint64_t, TQ::High, TQ::Low>,
            WriteTests::WritePtrNull<uint64_t, TQ::High, TQ::Mid>,
            WriteTests::WritePtrNull<uint64_t, TQ::High, TQ::High>,
            WriteTests::WritePtrNull<Helper, TQ::None, TQ::None>,
            WriteTests::WritePtrNull<Helper, TQ::None, TQ::VeryLow>,
            WriteTests::WritePtrNull<Helper, TQ::None, TQ::Low>,
            WriteTests::WritePtrNull<Helper, TQ::None, TQ::Mid>,
            WriteTests::WritePtrNull<Helper, TQ::None, TQ::High>,
            WriteTests::WritePtrNull<Helper, TQ::VeryLow, TQ::None>,
            WriteTests::WritePtrNull<Helper, TQ::VeryLow, TQ::VeryLow>,
            WriteTests::WritePtrNull<Helper, TQ::VeryLow, TQ::Low>,
            WriteTests::WritePtrNull<Helper, TQ::VeryLow, TQ::Mid>,
            WriteTests::WritePtrNull<Helper, TQ::VeryLow, TQ::High>,
            WriteTests::WritePtrNull<Helper, TQ::Low, TQ::None>,
            WriteTests::WritePtrNull<Helper, TQ::Low, TQ::VeryLow>,
            WriteTests::WritePtrNull<Helper, TQ::Low, TQ::Low>,
            WriteTests::WritePtrNull<Helper, TQ::Low, TQ::Mid>,
            WriteTests::WritePtrNull<Helper, TQ::Low, TQ::High>,
            WriteTests::WritePtrNull<Helper, TQ::Mid, TQ::None>,
            WriteTests::WritePtrNull<Helper, TQ::Mid, TQ::VeryLow>,
            WriteTests::WritePtrNull<Helper, TQ::Mid, TQ::Low>,
            WriteTests::WritePtrNull<Helper, TQ::Mid, TQ::Mid>,
            WriteTests::WritePtrNull<Helper, TQ::Mid, TQ::High>,
            WriteTests::WritePtrNull<Helper, TQ::High, TQ::None>,
            WriteTests::WritePtrNull<Helper, TQ::High, TQ::VeryLow>,
            WriteTests::WritePtrNull<Helper, TQ::High, TQ::Low>,
            WriteTests::WritePtrNull<Helper, TQ::High, TQ::Mid>,
            WriteTests::WritePtrNull<Helper, TQ::High, TQ::High>,

            WriteTests::WritePtr<uint8_t, TQ::None, TQ::None, false>,
            WriteTests::WritePtr<uint8_t, TQ::None, TQ::None, true>,
            WriteTests::WritePtr<uint8_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint8_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint8_t, TQ::None, TQ::Low, false>,
            WriteTests::WritePtr<uint8_t, TQ::None, TQ::Low, true>,
            WriteTests::WritePtr<uint8_t, TQ::None, TQ::Mid, false>,
            WriteTests::WritePtr<uint8_t, TQ::None, TQ::Mid, true>,
            WriteTests::WritePtr<uint8_t, TQ::None, TQ::High, false>,
            WriteTests::WritePtr<uint8_t, TQ::None, TQ::High, true>,
            WriteTests::WritePtr<uint8_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WritePtr<uint8_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WritePtr<uint8_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint8_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint8_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WritePtr<uint8_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WritePtr<uint8_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WritePtr<uint8_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WritePtr<uint8_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WritePtr<uint8_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WritePtr<uint8_t, TQ::Low, TQ::None, false>,
            WriteTests::WritePtr<uint8_t, TQ::Low, TQ::None, true>,
            WriteTests::WritePtr<uint8_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint8_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint8_t, TQ::Low, TQ::Low, false>,
            WriteTests::WritePtr<uint8_t, TQ::Low, TQ::Low, true>,
            WriteTests::WritePtr<uint8_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WritePtr<uint8_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WritePtr<uint8_t, TQ::Low, TQ::High, false>,
            WriteTests::WritePtr<uint8_t, TQ::Low, TQ::High, true>,
            WriteTests::WritePtr<uint8_t, TQ::Mid, TQ::None, false>,
            WriteTests::WritePtr<uint8_t, TQ::Mid, TQ::None, true>,
            WriteTests::WritePtr<uint8_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint8_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint8_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WritePtr<uint8_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WritePtr<uint8_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WritePtr<uint8_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WritePtr<uint8_t, TQ::Mid, TQ::High, false>,
            WriteTests::WritePtr<uint8_t, TQ::Mid, TQ::High, true>,
            WriteTests::WritePtr<uint8_t, TQ::High, TQ::None, false>,
            WriteTests::WritePtr<uint8_t, TQ::High, TQ::None, true>,
            WriteTests::WritePtr<uint8_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint8_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint8_t, TQ::High, TQ::Low, false>,
            WriteTests::WritePtr<uint8_t, TQ::High, TQ::Low, true>,
            WriteTests::WritePtr<uint8_t, TQ::High, TQ::Mid, false>,
            WriteTests::WritePtr<uint8_t, TQ::High, TQ::Mid, true>,
            WriteTests::WritePtr<uint8_t, TQ::High, TQ::High, false>,
            WriteTests::WritePtr<uint8_t, TQ::High, TQ::High, true>,
            WriteTests::WritePtr<uint16_t, TQ::None, TQ::None, false>,
            WriteTests::WritePtr<uint16_t, TQ::None, TQ::None, true>,
            WriteTests::WritePtr<uint16_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint16_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint16_t, TQ::None, TQ::Low, false>,
            WriteTests::WritePtr<uint16_t, TQ::None, TQ::Low, true>,
            WriteTests::WritePtr<uint16_t, TQ::None, TQ::Mid, false>,
            WriteTests::WritePtr<uint16_t, TQ::None, TQ::Mid, true>,
            WriteTests::WritePtr<uint16_t, TQ::None, TQ::High, false>,
            WriteTests::WritePtr<uint16_t, TQ::None, TQ::High, true>,
            WriteTests::WritePtr<uint16_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WritePtr<uint16_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WritePtr<uint16_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint16_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint16_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WritePtr<uint16_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WritePtr<uint16_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WritePtr<uint16_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WritePtr<uint16_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WritePtr<uint16_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WritePtr<uint16_t, TQ::Low, TQ::None, false>,
            WriteTests::WritePtr<uint16_t, TQ::Low, TQ::None, true>,
            WriteTests::WritePtr<uint16_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint16_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint16_t, TQ::Low, TQ::Low, false>,
            WriteTests::WritePtr<uint16_t, TQ::Low, TQ::Low, true>,
            WriteTests::WritePtr<uint16_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WritePtr<uint16_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WritePtr<uint16_t, TQ::Low, TQ::High, false>,
            WriteTests::WritePtr<uint16_t, TQ::Low, TQ::High, true>,
            WriteTests::WritePtr<uint16_t, TQ::Mid, TQ::None, false>,
            WriteTests::WritePtr<uint16_t, TQ::Mid, TQ::None, true>,
            WriteTests::WritePtr<uint16_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint16_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint16_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WritePtr<uint16_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WritePtr<uint16_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WritePtr<uint16_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WritePtr<uint16_t, TQ::Mid, TQ::High, false>,
            WriteTests::WritePtr<uint16_t, TQ::Mid, TQ::High, true>,
            WriteTests::WritePtr<uint16_t, TQ::High, TQ::None, false>,
            WriteTests::WritePtr<uint16_t, TQ::High, TQ::None, true>,
            WriteTests::WritePtr<uint16_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint16_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint16_t, TQ::High, TQ::Low, false>,
            WriteTests::WritePtr<uint16_t, TQ::High, TQ::Low, true>,
            WriteTests::WritePtr<uint16_t, TQ::High, TQ::Mid, false>,
            WriteTests::WritePtr<uint16_t, TQ::High, TQ::Mid, true>,
            WriteTests::WritePtr<uint16_t, TQ::High, TQ::High, false>,
            WriteTests::WritePtr<uint16_t, TQ::High, TQ::High, true>,
            WriteTests::WritePtr<uint32_t, TQ::None, TQ::None, false>,
            WriteTests::WritePtr<uint32_t, TQ::None, TQ::None, true>,
            WriteTests::WritePtr<uint32_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint32_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint32_t, TQ::None, TQ::Low, false>,
            WriteTests::WritePtr<uint32_t, TQ::None, TQ::Low, true>,
            WriteTests::WritePtr<uint32_t, TQ::None, TQ::Mid, false>,
            WriteTests::WritePtr<uint32_t, TQ::None, TQ::Mid, true>,
            WriteTests::WritePtr<uint32_t, TQ::None, TQ::High, false>,
            WriteTests::WritePtr<uint32_t, TQ::None, TQ::High, true>,
            WriteTests::WritePtr<uint32_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WritePtr<uint32_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WritePtr<uint32_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint32_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint32_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WritePtr<uint32_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WritePtr<uint32_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WritePtr<uint32_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WritePtr<uint32_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WritePtr<uint32_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WritePtr<uint32_t, TQ::Low, TQ::None, false>,
            WriteTests::WritePtr<uint32_t, TQ::Low, TQ::None, true>,
            WriteTests::WritePtr<uint32_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint32_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint32_t, TQ::Low, TQ::Low, false>,
            WriteTests::WritePtr<uint32_t, TQ::Low, TQ::Low, true>,
            WriteTests::WritePtr<uint32_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WritePtr<uint32_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WritePtr<uint32_t, TQ::Low, TQ::High, false>,
            WriteTests::WritePtr<uint32_t, TQ::Low, TQ::High, true>,
            WriteTests::WritePtr<uint32_t, TQ::Mid, TQ::None, false>,
            WriteTests::WritePtr<uint32_t, TQ::Mid, TQ::None, true>,
            WriteTests::WritePtr<uint32_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint32_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint32_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WritePtr<uint32_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WritePtr<uint32_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WritePtr<uint32_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WritePtr<uint32_t, TQ::Mid, TQ::High, false>,
            WriteTests::WritePtr<uint32_t, TQ::Mid, TQ::High, true>,
            WriteTests::WritePtr<uint32_t, TQ::High, TQ::None, false>,
            WriteTests::WritePtr<uint32_t, TQ::High, TQ::None, true>,
            WriteTests::WritePtr<uint32_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint32_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint32_t, TQ::High, TQ::Low, false>,
            WriteTests::WritePtr<uint32_t, TQ::High, TQ::Low, true>,
            WriteTests::WritePtr<uint32_t, TQ::High, TQ::Mid, false>,
            WriteTests::WritePtr<uint32_t, TQ::High, TQ::Mid, true>,
            WriteTests::WritePtr<uint32_t, TQ::High, TQ::High, false>,
            WriteTests::WritePtr<uint32_t, TQ::High, TQ::High, true>,
            WriteTests::WritePtr<uint64_t, TQ::None, TQ::None, false>,
            WriteTests::WritePtr<uint64_t, TQ::None, TQ::None, true>,
            WriteTests::WritePtr<uint64_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint64_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint64_t, TQ::None, TQ::Low, false>,
            WriteTests::WritePtr<uint64_t, TQ::None, TQ::Low, true>,
            WriteTests::WritePtr<uint64_t, TQ::None, TQ::Mid, false>,
            WriteTests::WritePtr<uint64_t, TQ::None, TQ::Mid, true>,
            WriteTests::WritePtr<uint64_t, TQ::None, TQ::High, false>,
            WriteTests::WritePtr<uint64_t, TQ::None, TQ::High, true>,
            WriteTests::WritePtr<uint64_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WritePtr<uint64_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WritePtr<uint64_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint64_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint64_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WritePtr<uint64_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WritePtr<uint64_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WritePtr<uint64_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WritePtr<uint64_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WritePtr<uint64_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WritePtr<uint64_t, TQ::Low, TQ::None, false>,
            WriteTests::WritePtr<uint64_t, TQ::Low, TQ::None, true>,
            WriteTests::WritePtr<uint64_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint64_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint64_t, TQ::Low, TQ::Low, false>,
            WriteTests::WritePtr<uint64_t, TQ::Low, TQ::Low, true>,
            WriteTests::WritePtr<uint64_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WritePtr<uint64_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WritePtr<uint64_t, TQ::Low, TQ::High, false>,
            WriteTests::WritePtr<uint64_t, TQ::Low, TQ::High, true>,
            WriteTests::WritePtr<uint64_t, TQ::Mid, TQ::None, false>,
            WriteTests::WritePtr<uint64_t, TQ::Mid, TQ::None, true>,
            WriteTests::WritePtr<uint64_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint64_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint64_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WritePtr<uint64_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WritePtr<uint64_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WritePtr<uint64_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WritePtr<uint64_t, TQ::Mid, TQ::High, false>,
            WriteTests::WritePtr<uint64_t, TQ::Mid, TQ::High, true>,
            WriteTests::WritePtr<uint64_t, TQ::High, TQ::None, false>,
            WriteTests::WritePtr<uint64_t, TQ::High, TQ::None, true>,
            WriteTests::WritePtr<uint64_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WritePtr<uint64_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WritePtr<uint64_t, TQ::High, TQ::Low, false>,
            WriteTests::WritePtr<uint64_t, TQ::High, TQ::Low, true>,
            WriteTests::WritePtr<uint64_t, TQ::High, TQ::Mid, false>,
            WriteTests::WritePtr<uint64_t, TQ::High, TQ::Mid, true>,
            WriteTests::WritePtr<uint64_t, TQ::High, TQ::High, false>,
            WriteTests::WritePtr<uint64_t, TQ::High, TQ::High, true>,
            WriteTests::WritePtr<Helper, TQ::None, TQ::None, false>,
            WriteTests::WritePtr<Helper, TQ::None, TQ::None, true>,
            WriteTests::WritePtr<Helper, TQ::None, TQ::VeryLow, false>,
            WriteTests::WritePtr<Helper, TQ::None, TQ::VeryLow, true>,
            WriteTests::WritePtr<Helper, TQ::None, TQ::Low, false>,
            WriteTests::WritePtr<Helper, TQ::None, TQ::Low, true>,
            WriteTests::WritePtr<Helper, TQ::None, TQ::Mid, false>,
            WriteTests::WritePtr<Helper, TQ::None, TQ::Mid, true>,
            WriteTests::WritePtr<Helper, TQ::None, TQ::High, false>,
            WriteTests::WritePtr<Helper, TQ::None, TQ::High, true>,
            WriteTests::WritePtr<Helper, TQ::VeryLow, TQ::None, false>,
            WriteTests::WritePtr<Helper, TQ::VeryLow, TQ::None, true>,
            WriteTests::WritePtr<Helper, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WritePtr<Helper, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WritePtr<Helper, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WritePtr<Helper, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WritePtr<Helper, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WritePtr<Helper, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WritePtr<Helper, TQ::VeryLow, TQ::High, false>,
            WriteTests::WritePtr<Helper, TQ::VeryLow, TQ::High, true>,
            WriteTests::WritePtr<Helper, TQ::Low, TQ::None, false>,
            WriteTests::WritePtr<Helper, TQ::Low, TQ::None, true>,
            WriteTests::WritePtr<Helper, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WritePtr<Helper, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WritePtr<Helper, TQ::Low, TQ::Low, false>,
            WriteTests::WritePtr<Helper, TQ::Low, TQ::Low, true>,
            WriteTests::WritePtr<Helper, TQ::Low, TQ::Mid, false>,
            WriteTests::WritePtr<Helper, TQ::Low, TQ::Mid, true>,
            WriteTests::WritePtr<Helper, TQ::Low, TQ::High, false>,
            WriteTests::WritePtr<Helper, TQ::Low, TQ::High, true>,
            WriteTests::WritePtr<Helper, TQ::Mid, TQ::None, false>,
            WriteTests::WritePtr<Helper, TQ::Mid, TQ::None, true>,
            WriteTests::WritePtr<Helper, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WritePtr<Helper, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WritePtr<Helper, TQ::Mid, TQ::Low, false>,
            WriteTests::WritePtr<Helper, TQ::Mid, TQ::Low, true>,
            WriteTests::WritePtr<Helper, TQ::Mid, TQ::Mid, false>,
            WriteTests::WritePtr<Helper, TQ::Mid, TQ::Mid, true>,
            WriteTests::WritePtr<Helper, TQ::Mid, TQ::High, false>,
            WriteTests::WritePtr<Helper, TQ::Mid, TQ::High, true>,
            WriteTests::WritePtr<Helper, TQ::High, TQ::None, false>,
            WriteTests::WritePtr<Helper, TQ::High, TQ::None, true>,
            WriteTests::WritePtr<Helper, TQ::High, TQ::VeryLow, false>,
            WriteTests::WritePtr<Helper, TQ::High, TQ::VeryLow, true>,
            WriteTests::WritePtr<Helper, TQ::High, TQ::Low, false>,
            WriteTests::WritePtr<Helper, TQ::High, TQ::Low, true>,
            WriteTests::WritePtr<Helper, TQ::High, TQ::Mid, false>,
            WriteTests::WritePtr<Helper, TQ::High, TQ::Mid, true>,
            WriteTests::WritePtr<Helper, TQ::High, TQ::High, false>,
            WriteTests::WritePtr<Helper, TQ::High, TQ::High, true>,

            WriteTests::WriteToWritePos<uint8_t, TQ::None, TQ::None, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::None, TQ::None, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::None, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::None, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::None, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::None, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::None, TQ::High, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::None, TQ::High, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Low, TQ::None, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Low, TQ::None, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Low, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Low, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Low, TQ::High, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Low, TQ::High, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Mid, TQ::None, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Mid, TQ::None, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Mid, TQ::High, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::Mid, TQ::High, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::High, TQ::None, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::High, TQ::None, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::High, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::High, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::High, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::High, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint8_t, TQ::High, TQ::High, false>,
            WriteTests::WriteToWritePos<uint8_t, TQ::High, TQ::High, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::None, TQ::None, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::None, TQ::None, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::None, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::None, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::None, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::None, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::None, TQ::High, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::None, TQ::High, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Low, TQ::None, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Low, TQ::None, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Low, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Low, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Low, TQ::High, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Low, TQ::High, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Mid, TQ::None, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Mid, TQ::None, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Mid, TQ::High, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::Mid, TQ::High, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::High, TQ::None, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::High, TQ::None, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::High, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::High, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::High, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::High, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint16_t, TQ::High, TQ::High, false>,
            WriteTests::WriteToWritePos<uint16_t, TQ::High, TQ::High, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::None, TQ::None, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::None, TQ::None, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::None, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::None, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::None, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::None, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::None, TQ::High, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::None, TQ::High, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Low, TQ::None, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Low, TQ::None, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Low, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Low, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Low, TQ::High, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Low, TQ::High, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Mid, TQ::None, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Mid, TQ::None, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Mid, TQ::High, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::Mid, TQ::High, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::High, TQ::None, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::High, TQ::None, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::High, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::High, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::High, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::High, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint32_t, TQ::High, TQ::High, false>,
            WriteTests::WriteToWritePos<uint32_t, TQ::High, TQ::High, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::None, TQ::None, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::None, TQ::None, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::None, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::None, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::None, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::None, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::None, TQ::High, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::None, TQ::High, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Low, TQ::None, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Low, TQ::None, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Low, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Low, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Low, TQ::High, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Low, TQ::High, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Mid, TQ::None, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Mid, TQ::None, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Mid, TQ::High, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::Mid, TQ::High, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::High, TQ::None, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::High, TQ::None, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::High, TQ::Low, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::High, TQ::Low, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::High, TQ::Mid, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::High, TQ::Mid, true>,
            WriteTests::WriteToWritePos<uint64_t, TQ::High, TQ::High, false>,
            WriteTests::WriteToWritePos<uint64_t, TQ::High, TQ::High, true>,
            WriteTests::WriteToWritePos<Helper, TQ::None, TQ::None, false>,
            WriteTests::WriteToWritePos<Helper, TQ::None, TQ::None, true>,
            WriteTests::WriteToWritePos<Helper, TQ::None, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<Helper, TQ::None, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<Helper, TQ::None, TQ::Low, false>,
            WriteTests::WriteToWritePos<Helper, TQ::None, TQ::Low, true>,
            WriteTests::WriteToWritePos<Helper, TQ::None, TQ::Mid, false>,
            WriteTests::WriteToWritePos<Helper, TQ::None, TQ::Mid, true>,
            WriteTests::WriteToWritePos<Helper, TQ::None, TQ::High, false>,
            WriteTests::WriteToWritePos<Helper, TQ::None, TQ::High, true>,
            WriteTests::WriteToWritePos<Helper, TQ::VeryLow, TQ::None, false>,
            WriteTests::WriteToWritePos<Helper, TQ::VeryLow, TQ::None, true>,
            WriteTests::WriteToWritePos<Helper, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<Helper, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<Helper, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WriteToWritePos<Helper, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WriteToWritePos<Helper, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WriteToWritePos<Helper, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WriteToWritePos<Helper, TQ::VeryLow, TQ::High, false>,
            WriteTests::WriteToWritePos<Helper, TQ::VeryLow, TQ::High, true>,
            WriteTests::WriteToWritePos<Helper, TQ::Low, TQ::None, false>,
            WriteTests::WriteToWritePos<Helper, TQ::Low, TQ::None, true>,
            WriteTests::WriteToWritePos<Helper, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<Helper, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<Helper, TQ::Low, TQ::Low, false>,
            WriteTests::WriteToWritePos<Helper, TQ::Low, TQ::Low, true>,
            WriteTests::WriteToWritePos<Helper, TQ::Low, TQ::Mid, false>,
            WriteTests::WriteToWritePos<Helper, TQ::Low, TQ::Mid, true>,
            WriteTests::WriteToWritePos<Helper, TQ::Low, TQ::High, false>,
            WriteTests::WriteToWritePos<Helper, TQ::Low, TQ::High, true>,
            WriteTests::WriteToWritePos<Helper, TQ::Mid, TQ::None, false>,
            WriteTests::WriteToWritePos<Helper, TQ::Mid, TQ::None, true>,
            WriteTests::WriteToWritePos<Helper, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<Helper, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<Helper, TQ::Mid, TQ::Low, false>,
            WriteTests::WriteToWritePos<Helper, TQ::Mid, TQ::Low, true>,
            WriteTests::WriteToWritePos<Helper, TQ::Mid, TQ::Mid, false>,
            WriteTests::WriteToWritePos<Helper, TQ::Mid, TQ::Mid, true>,
            WriteTests::WriteToWritePos<Helper, TQ::Mid, TQ::High, false>,
            WriteTests::WriteToWritePos<Helper, TQ::Mid, TQ::High, true>,
            WriteTests::WriteToWritePos<Helper, TQ::High, TQ::None, false>,
            WriteTests::WriteToWritePos<Helper, TQ::High, TQ::None, true>,
            WriteTests::WriteToWritePos<Helper, TQ::High, TQ::VeryLow, false>,
            WriteTests::WriteToWritePos<Helper, TQ::High, TQ::VeryLow, true>,
            WriteTests::WriteToWritePos<Helper, TQ::High, TQ::Low, false>,
            WriteTests::WriteToWritePos<Helper, TQ::High, TQ::Low, true>,
            WriteTests::WriteToWritePos<Helper, TQ::High, TQ::Mid, false>,
            WriteTests::WriteToWritePos<Helper, TQ::High, TQ::Mid, true>,
            WriteTests::WriteToWritePos<Helper, TQ::High, TQ::High, false>,
            WriteTests::WriteToWritePos<Helper, TQ::High, TQ::High, true>,

            WriteTests::WriteToEnd<uint8_t, TQ::None, TQ::None, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::None, TQ::None, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::None, TQ::Low, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::None, TQ::Low, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::None, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::None, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::None, TQ::High, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::None, TQ::High, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::Low, TQ::None, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::Low, TQ::None, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::Low, TQ::Low, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::Low, TQ::Low, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::Low, TQ::High, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::Low, TQ::High, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::Mid, TQ::None, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::Mid, TQ::None, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::Mid, TQ::High, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::Mid, TQ::High, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::High, TQ::None, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::High, TQ::None, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::High, TQ::Low, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::High, TQ::Low, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::High, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::High, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint8_t, TQ::High, TQ::High, false>,
            WriteTests::WriteToEnd<uint8_t, TQ::High, TQ::High, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::None, TQ::None, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::None, TQ::None, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::None, TQ::Low, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::None, TQ::Low, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::None, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::None, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::None, TQ::High, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::None, TQ::High, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::Low, TQ::None, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::Low, TQ::None, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::Low, TQ::Low, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::Low, TQ::Low, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::Low, TQ::High, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::Low, TQ::High, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::Mid, TQ::None, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::Mid, TQ::None, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::Mid, TQ::High, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::Mid, TQ::High, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::High, TQ::None, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::High, TQ::None, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::High, TQ::Low, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::High, TQ::Low, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::High, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::High, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint16_t, TQ::High, TQ::High, false>,
            WriteTests::WriteToEnd<uint16_t, TQ::High, TQ::High, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::None, TQ::None, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::None, TQ::None, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::None, TQ::Low, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::None, TQ::Low, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::None, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::None, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::None, TQ::High, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::None, TQ::High, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::Low, TQ::None, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::Low, TQ::None, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::Low, TQ::Low, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::Low, TQ::Low, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::Low, TQ::High, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::Low, TQ::High, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::Mid, TQ::None, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::Mid, TQ::None, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::Mid, TQ::High, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::Mid, TQ::High, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::High, TQ::None, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::High, TQ::None, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::High, TQ::Low, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::High, TQ::Low, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::High, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::High, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint32_t, TQ::High, TQ::High, false>,
            WriteTests::WriteToEnd<uint32_t, TQ::High, TQ::High, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::None, TQ::None, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::None, TQ::None, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::None, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::None, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::None, TQ::Low, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::None, TQ::Low, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::None, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::None, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::None, TQ::High, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::None, TQ::High, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::VeryLow, TQ::None, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::VeryLow, TQ::None, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::VeryLow, TQ::High, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::VeryLow, TQ::High, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::Low, TQ::None, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::Low, TQ::None, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::Low, TQ::Low, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::Low, TQ::Low, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::Low, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::Low, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::Low, TQ::High, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::Low, TQ::High, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::Mid, TQ::None, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::Mid, TQ::None, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::Mid, TQ::Low, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::Mid, TQ::Low, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::Mid, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::Mid, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::Mid, TQ::High, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::Mid, TQ::High, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::High, TQ::None, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::High, TQ::None, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::High, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::High, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::High, TQ::Low, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::High, TQ::Low, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::High, TQ::Mid, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::High, TQ::Mid, true>,
            WriteTests::WriteToEnd<uint64_t, TQ::High, TQ::High, false>,
            WriteTests::WriteToEnd<uint64_t, TQ::High, TQ::High, true>,
            WriteTests::WriteToEnd<Helper, TQ::None, TQ::None, false>,
            WriteTests::WriteToEnd<Helper, TQ::None, TQ::None, true>,
            WriteTests::WriteToEnd<Helper, TQ::None, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<Helper, TQ::None, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<Helper, TQ::None, TQ::Low, false>,
            WriteTests::WriteToEnd<Helper, TQ::None, TQ::Low, true>,
            WriteTests::WriteToEnd<Helper, TQ::None, TQ::Mid, false>,
            WriteTests::WriteToEnd<Helper, TQ::None, TQ::Mid, true>,
            WriteTests::WriteToEnd<Helper, TQ::None, TQ::High, false>,
            WriteTests::WriteToEnd<Helper, TQ::None, TQ::High, true>,
            WriteTests::WriteToEnd<Helper, TQ::VeryLow, TQ::None, false>,
            WriteTests::WriteToEnd<Helper, TQ::VeryLow, TQ::None, true>,
            WriteTests::WriteToEnd<Helper, TQ::VeryLow, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<Helper, TQ::VeryLow, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<Helper, TQ::VeryLow, TQ::Low, false>,
            WriteTests::WriteToEnd<Helper, TQ::VeryLow, TQ::Low, true>,
            WriteTests::WriteToEnd<Helper, TQ::VeryLow, TQ::Mid, false>,
            WriteTests::WriteToEnd<Helper, TQ::VeryLow, TQ::Mid, true>,
            WriteTests::WriteToEnd<Helper, TQ::VeryLow, TQ::High, false>,
            WriteTests::WriteToEnd<Helper, TQ::VeryLow, TQ::High, true>,
            WriteTests::WriteToEnd<Helper, TQ::Low, TQ::None, false>,
            WriteTests::WriteToEnd<Helper, TQ::Low, TQ::None, true>,
            WriteTests::WriteToEnd<Helper, TQ::Low, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<Helper, TQ::Low, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<Helper, TQ::Low, TQ::Low, false>,
            WriteTests::WriteToEnd<Helper, TQ::Low, TQ::Low, true>,
            WriteTests::WriteToEnd<Helper, TQ::Low, TQ::Mid, false>,
            WriteTests::WriteToEnd<Helper, TQ::Low, TQ::Mid, true>,
            WriteTests::WriteToEnd<Helper, TQ::Low, TQ::High, false>,
            WriteTests::WriteToEnd<Helper, TQ::Low, TQ::High, true>,
            WriteTests::WriteToEnd<Helper, TQ::Mid, TQ::None, false>,
            WriteTests::WriteToEnd<Helper, TQ::Mid, TQ::None, true>,
            WriteTests::WriteToEnd<Helper, TQ::Mid, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<Helper, TQ::Mid, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<Helper, TQ::Mid, TQ::Low, false>,
            WriteTests::WriteToEnd<Helper, TQ::Mid, TQ::Low, true>,
            WriteTests::WriteToEnd<Helper, TQ::Mid, TQ::Mid, false>,
            WriteTests::WriteToEnd<Helper, TQ::Mid, TQ::Mid, true>,
            WriteTests::WriteToEnd<Helper, TQ::Mid, TQ::High, false>,
            WriteTests::WriteToEnd<Helper, TQ::Mid, TQ::High, true>,
            WriteTests::WriteToEnd<Helper, TQ::High, TQ::None, false>,
            WriteTests::WriteToEnd<Helper, TQ::High, TQ::None, true>,
            WriteTests::WriteToEnd<Helper, TQ::High, TQ::VeryLow, false>,
            WriteTests::WriteToEnd<Helper, TQ::High, TQ::VeryLow, true>,
            WriteTests::WriteToEnd<Helper, TQ::High, TQ::Low, false>,
            WriteTests::WriteToEnd<Helper, TQ::High, TQ::Low, true>,
            WriteTests::WriteToEnd<Helper, TQ::High, TQ::Mid, false>,
            WriteTests::WriteToEnd<Helper, TQ::High, TQ::Mid, true>,
            WriteTests::WriteToEnd<Helper, TQ::High, TQ::High, false>,
            WriteTests::WriteToEnd<Helper, TQ::High, TQ::High, true>,
        };

        return tests;
    }
}