#include <CCDynamicBufferTests.h>


CC::DynamicBufferTests::UTList CC::DynamicBufferTests::GetTests()
{
#pragma warning(suppress : 6262) // Suppress high stack memory usage warning.
    static const UTList tests
    {
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint8_t, TQ::Zero, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint8_t, TQ::Zero, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint8_t, TQ::Zero, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint8_t, TQ::One, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint8_t, TQ::One, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint8_t, TQ::One, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint8_t, TQ::Many, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint8_t, TQ::Many, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint8_t, TQ::Many, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint16_t, TQ::Zero, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint16_t, TQ::Zero, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint16_t, TQ::Zero, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint16_t, TQ::One, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint16_t, TQ::One, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint16_t, TQ::One, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint16_t, TQ::Many, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint16_t, TQ::Many, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint16_t, TQ::Many, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint32_t, TQ::Zero, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint32_t, TQ::Zero, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint32_t, TQ::Zero, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint32_t, TQ::One, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint32_t, TQ::One, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint32_t, TQ::One, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint32_t, TQ::Many, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint32_t, TQ::Many, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint32_t, TQ::Many, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint64_t, TQ::Zero, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint64_t, TQ::Zero, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint64_t, TQ::Zero, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint64_t, TQ::One, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint64_t, TQ::One, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint64_t, TQ::One, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint64_t, TQ::Many, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint64_t, TQ::Many, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<uint64_t, TQ::Many, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<Helper, TQ::Zero, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<Helper, TQ::Zero, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<Helper, TQ::Zero, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<Helper, TQ::One, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<Helper, TQ::One, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<Helper, TQ::One, TQ::Many>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<Helper, TQ::Many, TQ::Zero>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<Helper, TQ::Many, TQ::One>,
        DynamicBufferTests::CalculateNewLengthTests::CalcNewLen<Helper, TQ::Many, TQ::Many>,

        DynamicBufferTests::WriteTests::WriteElement<uint8_t, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint8_t, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteElement<uint8_t, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint8_t, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteElement<uint8_t, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint8_t, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteElement<uint16_t, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint16_t, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteElement<uint16_t, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint16_t, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteElement<uint16_t, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint16_t, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteElement<uint32_t, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint32_t, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteElement<uint32_t, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint32_t, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteElement<uint32_t, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint32_t, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteElement<uint64_t, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint64_t, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteElement<uint64_t, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint64_t, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteElement<uint64_t, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteElement<uint64_t, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteElement<Helper, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteElement<Helper, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteElement<Helper, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteElement<Helper, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteElement<Helper, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteElement<Helper, TQ::Many, true>,

        DynamicBufferTests::WriteTests::WritePtrNull<uint8_t, TQ::Zero, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint8_t, TQ::Zero, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint8_t, TQ::Zero, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint8_t, TQ::One, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint8_t, TQ::One, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint8_t, TQ::One, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint8_t, TQ::Many, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint8_t, TQ::Many, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint8_t, TQ::Many, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint16_t, TQ::Zero, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint16_t, TQ::Zero, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint16_t, TQ::Zero, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint16_t, TQ::One, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint16_t, TQ::One, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint16_t, TQ::One, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint16_t, TQ::Many, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint16_t, TQ::Many, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint16_t, TQ::Many, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint32_t, TQ::Zero, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint32_t, TQ::Zero, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint32_t, TQ::Zero, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint32_t, TQ::One, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint32_t, TQ::One, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint32_t, TQ::One, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint32_t, TQ::Many, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint32_t, TQ::Many, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint32_t, TQ::Many, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint64_t, TQ::Zero, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint64_t, TQ::Zero, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint64_t, TQ::Zero, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint64_t, TQ::One, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint64_t, TQ::One, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint64_t, TQ::One, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint64_t, TQ::Many, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint64_t, TQ::Many, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<uint64_t, TQ::Many, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<Helper, TQ::Zero, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<Helper, TQ::Zero, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<Helper, TQ::Zero, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<Helper, TQ::One, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<Helper, TQ::One, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<Helper, TQ::One, TQ::Many>,
        DynamicBufferTests::WriteTests::WritePtrNull<Helper, TQ::Many, TQ::Zero>,
        DynamicBufferTests::WriteTests::WritePtrNull<Helper, TQ::Many, TQ::One>,
        DynamicBufferTests::WriteTests::WritePtrNull<Helper, TQ::Many, TQ::Many>,

        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint8_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint16_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint32_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<uint64_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WritePtr<Helper, TQ::Many, TQ::Many, true>,

        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint8_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint16_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint32_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<uint64_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToWritePos<Helper, TQ::Many, TQ::Many, true>,

        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint8_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint16_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint32_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<uint64_t, TQ::Many, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Zero, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Zero, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Zero, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Zero, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Zero, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Zero, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::One, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::One, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::One, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::One, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::One, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::One, TQ::Many, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Many, TQ::Zero, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Many, TQ::Zero, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Many, TQ::One, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Many, TQ::One, true>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Many, TQ::Many, false>,
        DynamicBufferTests::WriteTests::WriteToEnd<Helper, TQ::Many, TQ::Many, true>,
    };

    return tests;
}
