#include <CCPointerTests.h>

CC::PointerTests::UTList CC::PointerTests::GetTests( )
{
    using TQ = TestQuantity;

    static const UTList tests
    {
        PointerTests::DeallocationTests::CopyPointerObj<uint8_t, TQ::Zero>,
        PointerTests::DeallocationTests::CopyPointerObj<uint8_t, TQ::One>,
        PointerTests::DeallocationTests::CopyPointerObj<uint8_t, TQ::Many>,
        PointerTests::DeallocationTests::CopyPointerObj<uint16_t, TQ::Zero>,
        PointerTests::DeallocationTests::CopyPointerObj<uint16_t, TQ::One>,
        PointerTests::DeallocationTests::CopyPointerObj<uint16_t, TQ::Many>,
        PointerTests::DeallocationTests::CopyPointerObj<uint32_t, TQ::Zero>,
        PointerTests::DeallocationTests::CopyPointerObj<uint32_t, TQ::One>,
        PointerTests::DeallocationTests::CopyPointerObj<uint32_t, TQ::Many>,
        PointerTests::DeallocationTests::CopyPointerObj<uint64_t, TQ::Zero>,
        PointerTests::DeallocationTests::CopyPointerObj<uint64_t, TQ::One>,
        PointerTests::DeallocationTests::CopyPointerObj<uint64_t, TQ::Many>,
        PointerTests::DeallocationTests::CopyPointerObj<Helper, TQ::Zero>,
        PointerTests::DeallocationTests::CopyPointerObj<Helper, TQ::One>,
        PointerTests::DeallocationTests::CopyPointerObj<Helper, TQ::Many>,

        PointerTests::DeallocationTests::TransferPointerObj<uint8_t, TQ::Zero>,
        PointerTests::DeallocationTests::TransferPointerObj<uint8_t, TQ::One>,
        PointerTests::DeallocationTests::TransferPointerObj<uint8_t, TQ::Many>,
        PointerTests::DeallocationTests::TransferPointerObj<uint16_t, TQ::Zero>,
        PointerTests::DeallocationTests::TransferPointerObj<uint16_t, TQ::One>,
        PointerTests::DeallocationTests::TransferPointerObj<uint16_t, TQ::Many>,
        PointerTests::DeallocationTests::TransferPointerObj<uint32_t, TQ::Zero>,
        PointerTests::DeallocationTests::TransferPointerObj<uint32_t, TQ::One>,
        PointerTests::DeallocationTests::TransferPointerObj<uint32_t, TQ::Many>,
        PointerTests::DeallocationTests::TransferPointerObj<uint64_t, TQ::Zero>,
        PointerTests::DeallocationTests::TransferPointerObj<uint64_t, TQ::One>,
        PointerTests::DeallocationTests::TransferPointerObj<uint64_t, TQ::Many>,
        PointerTests::DeallocationTests::TransferPointerObj<Helper, TQ::Zero>,
        PointerTests::DeallocationTests::TransferPointerObj<Helper, TQ::One>,
        PointerTests::DeallocationTests::TransferPointerObj<Helper, TQ::Many>,

        PointerTests::DeallocationTests::Destructor<uint8_t, TQ::Zero>,
        PointerTests::DeallocationTests::Destructor<uint8_t, TQ::One>,
        PointerTests::DeallocationTests::Destructor<uint8_t, TQ::Many>,
        PointerTests::DeallocationTests::Destructor<uint16_t, TQ::Zero>,
        PointerTests::DeallocationTests::Destructor<uint16_t, TQ::One>,
        PointerTests::DeallocationTests::Destructor<uint16_t, TQ::Many>,
        PointerTests::DeallocationTests::Destructor<uint32_t, TQ::Zero>,
        PointerTests::DeallocationTests::Destructor<uint32_t, TQ::One>,
        PointerTests::DeallocationTests::Destructor<uint32_t, TQ::Many>,
        PointerTests::DeallocationTests::Destructor<uint64_t, TQ::Zero>,
        PointerTests::DeallocationTests::Destructor<uint64_t, TQ::One>,
        PointerTests::DeallocationTests::Destructor<uint64_t, TQ::Many>,
        PointerTests::DeallocationTests::Destructor<Helper, TQ::Zero>,
        PointerTests::DeallocationTests::Destructor<Helper, TQ::One>,
        PointerTests::DeallocationTests::Destructor<Helper, TQ::Many>,

        PointerTests::DeallocationTests::Free<uint8_t, TQ::Zero>,
        PointerTests::DeallocationTests::Free<uint8_t, TQ::One>,
        PointerTests::DeallocationTests::Free<uint8_t, TQ::Many>,
        PointerTests::DeallocationTests::Free<uint16_t, TQ::Zero>,
        PointerTests::DeallocationTests::Free<uint16_t, TQ::One>,
        PointerTests::DeallocationTests::Free<uint16_t, TQ::Many>,
        PointerTests::DeallocationTests::Free<uint32_t, TQ::Zero>,
        PointerTests::DeallocationTests::Free<uint32_t, TQ::One>,
        PointerTests::DeallocationTests::Free<uint32_t, TQ::Many>,
        PointerTests::DeallocationTests::Free<uint64_t, TQ::Zero>,
        PointerTests::DeallocationTests::Free<uint64_t, TQ::One>,
        PointerTests::DeallocationTests::Free<uint64_t, TQ::Many>,
        PointerTests::DeallocationTests::Free<Helper, TQ::Zero>,
        PointerTests::DeallocationTests::Free<Helper, TQ::One>,
        PointerTests::DeallocationTests::Free<Helper, TQ::Many>,

        PointerTests::ConstructorTests::DefaultCtor<uint8_t>,
        PointerTests::ConstructorTests::DefaultCtor<uint16_t>,
        PointerTests::ConstructorTests::DefaultCtor<uint32_t>,
        PointerTests::ConstructorTests::DefaultCtor<uint64_t>,
        PointerTests::ConstructorTests::DefaultCtor<Helper>,

        PointerTests::ConstructorTests::LengthCtor<uint8_t, TQ::Zero>,
        PointerTests::ConstructorTests::LengthCtor<uint8_t, TQ::One>,
        PointerTests::ConstructorTests::LengthCtor<uint8_t, TQ::Many>,
        PointerTests::ConstructorTests::LengthCtor<uint16_t, TQ::Zero>,
        PointerTests::ConstructorTests::LengthCtor<uint16_t, TQ::One>,
        PointerTests::ConstructorTests::LengthCtor<uint16_t, TQ::Many>,
        PointerTests::ConstructorTests::LengthCtor<uint32_t, TQ::Zero>,
        PointerTests::ConstructorTests::LengthCtor<uint32_t, TQ::One>,
        PointerTests::ConstructorTests::LengthCtor<uint32_t, TQ::Many>,
        PointerTests::ConstructorTests::LengthCtor<uint64_t, TQ::Zero>,
        PointerTests::ConstructorTests::LengthCtor<uint64_t, TQ::One>,
        PointerTests::ConstructorTests::LengthCtor<uint64_t, TQ::Many>,
        PointerTests::ConstructorTests::LengthCtor<Helper, TQ::Zero>,
        PointerTests::ConstructorTests::LengthCtor<Helper, TQ::One>,
        PointerTests::ConstructorTests::LengthCtor<Helper, TQ::Many>,

        PointerTests::ConstructorTests::RawPointerCopyCtor<uint8_t, TQ::Zero>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<uint8_t, TQ::One>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<uint8_t, TQ::Many>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<uint16_t, TQ::Zero>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<uint16_t, TQ::One>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<uint16_t, TQ::Many>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<uint32_t, TQ::Zero>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<uint32_t, TQ::One>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<uint32_t, TQ::Many>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<uint64_t, TQ::Zero>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<uint64_t, TQ::One>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<uint64_t, TQ::Many>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<Helper, TQ::Zero>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<Helper, TQ::One>,
        PointerTests::ConstructorTests::RawPointerCopyCtor<Helper, TQ::Many>,

        PointerTests::ConstructorTests::RawPointerStealCtor<uint8_t, TQ::Zero>,
        PointerTests::ConstructorTests::RawPointerStealCtor<uint8_t, TQ::One>,
        PointerTests::ConstructorTests::RawPointerStealCtor<uint8_t, TQ::Many>,
        PointerTests::ConstructorTests::RawPointerStealCtor<uint16_t, TQ::Zero>,
        PointerTests::ConstructorTests::RawPointerStealCtor<uint16_t, TQ::One>,
        PointerTests::ConstructorTests::RawPointerStealCtor<uint16_t, TQ::Many>,
        PointerTests::ConstructorTests::RawPointerStealCtor<uint32_t, TQ::Zero>,
        PointerTests::ConstructorTests::RawPointerStealCtor<uint32_t, TQ::One>,
        PointerTests::ConstructorTests::RawPointerStealCtor<uint32_t, TQ::Many>,
        PointerTests::ConstructorTests::RawPointerStealCtor<uint64_t, TQ::Zero>,
        PointerTests::ConstructorTests::RawPointerStealCtor<uint64_t, TQ::One>,
        PointerTests::ConstructorTests::RawPointerStealCtor<uint64_t, TQ::Many>,
        PointerTests::ConstructorTests::RawPointerStealCtor<Helper, TQ::Zero>,
        PointerTests::ConstructorTests::RawPointerStealCtor<Helper, TQ::One>,
        PointerTests::ConstructorTests::RawPointerStealCtor<Helper, TQ::Many>,

        PointerTests::ConstructorTests::CopyCtor<uint8_t, TQ::Zero>,
        PointerTests::ConstructorTests::CopyCtor<uint8_t, TQ::One>,
        PointerTests::ConstructorTests::CopyCtor<uint8_t, TQ::Many>,
        PointerTests::ConstructorTests::CopyCtor<uint16_t, TQ::Zero>,
        PointerTests::ConstructorTests::CopyCtor<uint16_t, TQ::One>,
        PointerTests::ConstructorTests::CopyCtor<uint16_t, TQ::Many>,
        PointerTests::ConstructorTests::CopyCtor<uint32_t, TQ::Zero>,
        PointerTests::ConstructorTests::CopyCtor<uint32_t, TQ::One>,
        PointerTests::ConstructorTests::CopyCtor<uint32_t, TQ::Many>,
        PointerTests::ConstructorTests::CopyCtor<uint64_t, TQ::Zero>,
        PointerTests::ConstructorTests::CopyCtor<uint64_t, TQ::One>,
        PointerTests::ConstructorTests::CopyCtor<uint64_t, TQ::Many>,
        PointerTests::ConstructorTests::CopyCtor<Helper, TQ::Zero>,
        PointerTests::ConstructorTests::CopyCtor<Helper, TQ::One>,
        PointerTests::ConstructorTests::CopyCtor<Helper, TQ::Many>,

        PointerTests::ConstructorTests::MoveCtor<uint8_t, TQ::Zero>,
        PointerTests::ConstructorTests::MoveCtor<uint8_t, TQ::One>,
        PointerTests::ConstructorTests::MoveCtor<uint8_t, TQ::Many>,
        PointerTests::ConstructorTests::MoveCtor<uint16_t, TQ::Zero>,
        PointerTests::ConstructorTests::MoveCtor<uint16_t, TQ::One>,
        PointerTests::ConstructorTests::MoveCtor<uint16_t, TQ::Many>,
        PointerTests::ConstructorTests::MoveCtor<uint32_t, TQ::Zero>,
        PointerTests::ConstructorTests::MoveCtor<uint32_t, TQ::One>,
        PointerTests::ConstructorTests::MoveCtor<uint32_t, TQ::Many>,
        PointerTests::ConstructorTests::MoveCtor<uint64_t, TQ::Zero>,
        PointerTests::ConstructorTests::MoveCtor<uint64_t, TQ::One>,
        PointerTests::ConstructorTests::MoveCtor<uint64_t, TQ::Many>,
        PointerTests::ConstructorTests::MoveCtor<Helper, TQ::Zero>,
        PointerTests::ConstructorTests::MoveCtor<Helper, TQ::One>,
        PointerTests::ConstructorTests::MoveCtor<Helper, TQ::Many>,

        PointerTests::CopyTests::CopyAssignment<uint8_t, TQ::Zero, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint8_t, TQ::Zero, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint8_t, TQ::Zero, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<uint8_t, TQ::One, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint8_t, TQ::One, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint8_t, TQ::One, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<uint8_t, TQ::Many, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint8_t, TQ::Many, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint8_t, TQ::Many, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<uint16_t, TQ::Zero, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint16_t, TQ::Zero, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint16_t, TQ::Zero, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<uint16_t, TQ::One, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint16_t, TQ::One, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint16_t, TQ::One, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<uint16_t, TQ::Many, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint16_t, TQ::Many, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint16_t, TQ::Many, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<uint32_t, TQ::Zero, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint32_t, TQ::Zero, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint32_t, TQ::Zero, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<uint32_t, TQ::One, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint32_t, TQ::One, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint32_t, TQ::One, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<uint32_t, TQ::Many, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint32_t, TQ::Many, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint32_t, TQ::Many, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<uint64_t, TQ::Zero, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint64_t, TQ::Zero, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint64_t, TQ::Zero, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<uint64_t, TQ::One, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint64_t, TQ::One, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint64_t, TQ::One, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<uint64_t, TQ::Many, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<uint64_t, TQ::Many, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<uint64_t, TQ::Many, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<Helper, TQ::Zero, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<Helper, TQ::Zero, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<Helper, TQ::Zero, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<Helper, TQ::One, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<Helper, TQ::One, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<Helper, TQ::One, TQ::Many>,
        PointerTests::CopyTests::CopyAssignment<Helper, TQ::Many, TQ::Zero>,
        PointerTests::CopyTests::CopyAssignment<Helper, TQ::Many, TQ::One>,
        PointerTests::CopyTests::CopyAssignment<Helper, TQ::Many, TQ::Many>,

        PointerTests::MoveTests::MoveAssignment<uint8_t, TQ::Zero, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint8_t, TQ::Zero, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint8_t, TQ::Zero, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<uint8_t, TQ::One, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint8_t, TQ::One, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint8_t, TQ::One, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<uint8_t, TQ::Many, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint8_t, TQ::Many, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint8_t, TQ::Many, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<uint16_t, TQ::Zero, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint16_t, TQ::Zero, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint16_t, TQ::Zero, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<uint16_t, TQ::One, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint16_t, TQ::One, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint16_t, TQ::One, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<uint16_t, TQ::Many, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint16_t, TQ::Many, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint16_t, TQ::Many, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<uint32_t, TQ::Zero, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint32_t, TQ::Zero, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint32_t, TQ::Zero, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<uint32_t, TQ::One, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint32_t, TQ::One, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint32_t, TQ::One, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<uint32_t, TQ::Many, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint32_t, TQ::Many, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint32_t, TQ::Many, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<uint64_t, TQ::Zero, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint64_t, TQ::Zero, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint64_t, TQ::Zero, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<uint64_t, TQ::One, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint64_t, TQ::One, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint64_t, TQ::One, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<uint64_t, TQ::Many, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<uint64_t, TQ::Many, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<uint64_t, TQ::Many, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<Helper, TQ::Zero, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<Helper, TQ::Zero, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<Helper, TQ::Zero, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<Helper, TQ::One, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<Helper, TQ::One, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<Helper, TQ::One, TQ::Many>,
        PointerTests::MoveTests::MoveAssignment<Helper, TQ::Many, TQ::Zero>,
        PointerTests::MoveTests::MoveAssignment<Helper, TQ::Many, TQ::One>,
        PointerTests::MoveTests::MoveAssignment<Helper, TQ::Many, TQ::Many>,

        PointerTests::DereferenceOperatorTests::Dereference<uint8_t, TQ::Zero>,
        PointerTests::DereferenceOperatorTests::Dereference<uint8_t, TQ::One>,
        PointerTests::DereferenceOperatorTests::Dereference<uint8_t, TQ::Many>,
        PointerTests::DereferenceOperatorTests::Dereference<uint16_t, TQ::Zero>,
        PointerTests::DereferenceOperatorTests::Dereference<uint16_t, TQ::One>,
        PointerTests::DereferenceOperatorTests::Dereference<uint16_t, TQ::Many>,
        PointerTests::DereferenceOperatorTests::Dereference<uint32_t, TQ::Zero>,
        PointerTests::DereferenceOperatorTests::Dereference<uint32_t, TQ::One>,
        PointerTests::DereferenceOperatorTests::Dereference<uint32_t, TQ::Many>,
        PointerTests::DereferenceOperatorTests::Dereference<uint64_t, TQ::Zero>,
        PointerTests::DereferenceOperatorTests::Dereference<uint64_t, TQ::One>,
        PointerTests::DereferenceOperatorTests::Dereference<uint64_t, TQ::Many>,
        PointerTests::DereferenceOperatorTests::Dereference<Helper, TQ::Zero>,
        PointerTests::DereferenceOperatorTests::Dereference<Helper, TQ::One>,
        PointerTests::DereferenceOperatorTests::Dereference<Helper, TQ::Many>
    };

    return tests;
}