#include <CCPointerTests.h>

CC::PointerTests::UTList CC::PointerTests::GetTests()
{
    using TQ = TestQuantity;

    static const UTList tests
    {
        DeallocationTests::CopyPointerObj<uint8_t, TQ::None>,
        DeallocationTests::CopyPointerObj<uint8_t, TQ::VeryLow>,
        DeallocationTests::CopyPointerObj<uint8_t, TQ::Low>,
        DeallocationTests::CopyPointerObj<uint8_t, TQ::Mid>,
        DeallocationTests::CopyPointerObj<uint8_t, TQ::High>,
        DeallocationTests::CopyPointerObj<uint16_t, TQ::None>,
        DeallocationTests::CopyPointerObj<uint16_t, TQ::VeryLow>,
        DeallocationTests::CopyPointerObj<uint16_t, TQ::Low>,
        DeallocationTests::CopyPointerObj<uint16_t, TQ::Mid>,
        DeallocationTests::CopyPointerObj<uint16_t, TQ::High>,
        DeallocationTests::CopyPointerObj<uint32_t, TQ::None>,
        DeallocationTests::CopyPointerObj<uint32_t, TQ::VeryLow>,
        DeallocationTests::CopyPointerObj<uint32_t, TQ::Low>,
        DeallocationTests::CopyPointerObj<uint32_t, TQ::Mid>,
        DeallocationTests::CopyPointerObj<uint32_t, TQ::High>,
        DeallocationTests::CopyPointerObj<uint64_t, TQ::None>,
        DeallocationTests::CopyPointerObj<uint64_t, TQ::VeryLow>,
        DeallocationTests::CopyPointerObj<uint64_t, TQ::Low>,
        DeallocationTests::CopyPointerObj<uint64_t, TQ::Mid>,
        DeallocationTests::CopyPointerObj<uint64_t, TQ::High>,
        DeallocationTests::CopyPointerObj<Helper, TQ::None>,
        DeallocationTests::CopyPointerObj<Helper, TQ::VeryLow>,
        DeallocationTests::CopyPointerObj<Helper, TQ::Low>,
        DeallocationTests::CopyPointerObj<Helper, TQ::Mid>,
        DeallocationTests::CopyPointerObj<Helper, TQ::High>,

        DeallocationTests::TransferPointerObj<uint8_t, TQ::None>,
        DeallocationTests::TransferPointerObj<uint8_t, TQ::VeryLow>,
        DeallocationTests::TransferPointerObj<uint8_t, TQ::Low>,
        DeallocationTests::TransferPointerObj<uint8_t, TQ::Mid>,
        DeallocationTests::TransferPointerObj<uint8_t, TQ::High>,
        DeallocationTests::TransferPointerObj<uint16_t, TQ::None>,
        DeallocationTests::TransferPointerObj<uint16_t, TQ::VeryLow>,
        DeallocationTests::TransferPointerObj<uint16_t, TQ::Low>,
        DeallocationTests::TransferPointerObj<uint16_t, TQ::Mid>,
        DeallocationTests::TransferPointerObj<uint16_t, TQ::High>,
        DeallocationTests::TransferPointerObj<uint32_t, TQ::None>,
        DeallocationTests::TransferPointerObj<uint32_t, TQ::VeryLow>,
        DeallocationTests::TransferPointerObj<uint32_t, TQ::Low>,
        DeallocationTests::TransferPointerObj<uint32_t, TQ::Mid>,
        DeallocationTests::TransferPointerObj<uint32_t, TQ::High>,
        DeallocationTests::TransferPointerObj<uint64_t, TQ::None>,
        DeallocationTests::TransferPointerObj<uint64_t, TQ::VeryLow>,
        DeallocationTests::TransferPointerObj<uint64_t, TQ::Low>,
        DeallocationTests::TransferPointerObj<uint64_t, TQ::Mid>,
        DeallocationTests::TransferPointerObj<uint64_t, TQ::High>,
        DeallocationTests::TransferPointerObj<Helper, TQ::None>,
        DeallocationTests::TransferPointerObj<Helper, TQ::VeryLow>,
        DeallocationTests::TransferPointerObj<Helper, TQ::Low>,
        DeallocationTests::TransferPointerObj<Helper, TQ::Mid>,
        DeallocationTests::TransferPointerObj<Helper, TQ::High>,

        DeallocationTests::Destructor<uint8_t, TQ::None>,
        DeallocationTests::Destructor<uint8_t, TQ::VeryLow>,
        DeallocationTests::Destructor<uint8_t, TQ::Low>,
        DeallocationTests::Destructor<uint8_t, TQ::Mid>,
        DeallocationTests::Destructor<uint8_t, TQ::High>,
        DeallocationTests::Destructor<uint16_t, TQ::None>,
        DeallocationTests::Destructor<uint16_t, TQ::VeryLow>,
        DeallocationTests::Destructor<uint16_t, TQ::Low>,
        DeallocationTests::Destructor<uint16_t, TQ::Mid>,
        DeallocationTests::Destructor<uint16_t, TQ::High>,
        DeallocationTests::Destructor<uint32_t, TQ::None>,
        DeallocationTests::Destructor<uint32_t, TQ::VeryLow>,
        DeallocationTests::Destructor<uint32_t, TQ::Low>,
        DeallocationTests::Destructor<uint32_t, TQ::Mid>,
        DeallocationTests::Destructor<uint32_t, TQ::High>,
        DeallocationTests::Destructor<uint64_t, TQ::None>,
        DeallocationTests::Destructor<uint64_t, TQ::VeryLow>,
        DeallocationTests::Destructor<uint64_t, TQ::Low>,
        DeallocationTests::Destructor<uint64_t, TQ::Mid>,
        DeallocationTests::Destructor<uint64_t, TQ::High>,
        DeallocationTests::Destructor<Helper, TQ::None>,
        DeallocationTests::Destructor<Helper, TQ::VeryLow>,
        DeallocationTests::Destructor<Helper, TQ::Low>,
        DeallocationTests::Destructor<Helper, TQ::Mid>,
        DeallocationTests::Destructor<Helper, TQ::High>,

        DeallocationTests::Free<uint8_t, TQ::None>,
        DeallocationTests::Free<uint8_t, TQ::VeryLow>,
        DeallocationTests::Free<uint8_t, TQ::Low>,
        DeallocationTests::Free<uint8_t, TQ::Mid>,
        DeallocationTests::Free<uint8_t, TQ::High>,
        DeallocationTests::Free<uint16_t, TQ::None>,
        DeallocationTests::Free<uint16_t, TQ::VeryLow>,
        DeallocationTests::Free<uint16_t, TQ::Low>,
        DeallocationTests::Free<uint16_t, TQ::Mid>,
        DeallocationTests::Free<uint16_t, TQ::High>,
        DeallocationTests::Free<uint32_t, TQ::None>,
        DeallocationTests::Free<uint32_t, TQ::VeryLow>,
        DeallocationTests::Free<uint32_t, TQ::Low>,
        DeallocationTests::Free<uint32_t, TQ::Mid>,
        DeallocationTests::Free<uint32_t, TQ::High>,
        DeallocationTests::Free<uint64_t, TQ::None>,
        DeallocationTests::Free<uint64_t, TQ::VeryLow>,
        DeallocationTests::Free<uint64_t, TQ::Low>,
        DeallocationTests::Free<uint64_t, TQ::Mid>,
        DeallocationTests::Free<uint64_t, TQ::High>,
        DeallocationTests::Free<Helper, TQ::None>,
        DeallocationTests::Free<Helper, TQ::VeryLow>,
        DeallocationTests::Free<Helper, TQ::Low>,
        DeallocationTests::Free<Helper, TQ::Mid>,
        DeallocationTests::Free<Helper, TQ::High>,

        ConstructorTests::DefaultCtor<uint8_t>,
        ConstructorTests::DefaultCtor<uint16_t>,
        ConstructorTests::DefaultCtor<uint32_t>,
        ConstructorTests::DefaultCtor<uint64_t>,
        ConstructorTests::DefaultCtor<Helper>,

        ConstructorTests::LengthCtor<uint8_t, TQ::None>,
        ConstructorTests::LengthCtor<uint8_t, TQ::VeryLow>,
        ConstructorTests::LengthCtor<uint8_t, TQ::Low>,
        ConstructorTests::LengthCtor<uint8_t, TQ::Mid>,
        ConstructorTests::LengthCtor<uint8_t, TQ::High>,
        ConstructorTests::LengthCtor<uint16_t, TQ::None>,
        ConstructorTests::LengthCtor<uint16_t, TQ::VeryLow>,
        ConstructorTests::LengthCtor<uint16_t, TQ::Low>,
        ConstructorTests::LengthCtor<uint16_t, TQ::Mid>,
        ConstructorTests::LengthCtor<uint16_t, TQ::High>,
        ConstructorTests::LengthCtor<uint32_t, TQ::None>,
        ConstructorTests::LengthCtor<uint32_t, TQ::VeryLow>,
        ConstructorTests::LengthCtor<uint32_t, TQ::Low>,
        ConstructorTests::LengthCtor<uint32_t, TQ::Mid>,
        ConstructorTests::LengthCtor<uint32_t, TQ::High>,
        ConstructorTests::LengthCtor<uint64_t, TQ::None>,
        ConstructorTests::LengthCtor<uint64_t, TQ::VeryLow>,
        ConstructorTests::LengthCtor<uint64_t, TQ::Low>,
        ConstructorTests::LengthCtor<uint64_t, TQ::Mid>,
        ConstructorTests::LengthCtor<uint64_t, TQ::High>,
        ConstructorTests::LengthCtor<Helper, TQ::None>,
        ConstructorTests::LengthCtor<Helper, TQ::VeryLow>,
        ConstructorTests::LengthCtor<Helper, TQ::Low>,
        ConstructorTests::LengthCtor<Helper, TQ::Mid>,
        ConstructorTests::LengthCtor<Helper, TQ::High>,

        ConstructorTests::RawPointerCopyCtor<uint8_t, TQ::None>,
        ConstructorTests::RawPointerCopyCtor<uint8_t, TQ::VeryLow>,
        ConstructorTests::RawPointerCopyCtor<uint8_t, TQ::Low>,
        ConstructorTests::RawPointerCopyCtor<uint8_t, TQ::Mid>,
        ConstructorTests::RawPointerCopyCtor<uint8_t, TQ::High>,
        ConstructorTests::RawPointerCopyCtor<uint16_t, TQ::None>,
        ConstructorTests::RawPointerCopyCtor<uint16_t, TQ::VeryLow>,
        ConstructorTests::RawPointerCopyCtor<uint16_t, TQ::Low>,
        ConstructorTests::RawPointerCopyCtor<uint16_t, TQ::Mid>,
        ConstructorTests::RawPointerCopyCtor<uint16_t, TQ::High>,
        ConstructorTests::RawPointerCopyCtor<uint32_t, TQ::None>,
        ConstructorTests::RawPointerCopyCtor<uint32_t, TQ::VeryLow>,
        ConstructorTests::RawPointerCopyCtor<uint32_t, TQ::Low>,
        ConstructorTests::RawPointerCopyCtor<uint32_t, TQ::Mid>,
        ConstructorTests::RawPointerCopyCtor<uint32_t, TQ::High>,
        ConstructorTests::RawPointerCopyCtor<uint64_t, TQ::None>,
        ConstructorTests::RawPointerCopyCtor<uint64_t, TQ::VeryLow>,
        ConstructorTests::RawPointerCopyCtor<uint64_t, TQ::Low>,
        ConstructorTests::RawPointerCopyCtor<uint64_t, TQ::Mid>,
        ConstructorTests::RawPointerCopyCtor<uint64_t, TQ::High>,
        ConstructorTests::RawPointerCopyCtor<Helper, TQ::None>,
        ConstructorTests::RawPointerCopyCtor<Helper, TQ::VeryLow>,
        ConstructorTests::RawPointerCopyCtor<Helper, TQ::Low>,
        ConstructorTests::RawPointerCopyCtor<Helper, TQ::Mid>,
        ConstructorTests::RawPointerCopyCtor<Helper, TQ::High>,

        ConstructorTests::RawPointerStealCtor<uint8_t, TQ::None>,
        ConstructorTests::RawPointerStealCtor<uint8_t, TQ::VeryLow>,
        ConstructorTests::RawPointerStealCtor<uint8_t, TQ::Low>,
        ConstructorTests::RawPointerStealCtor<uint8_t, TQ::Mid>,
        ConstructorTests::RawPointerStealCtor<uint8_t, TQ::High>,
        ConstructorTests::RawPointerStealCtor<uint16_t, TQ::None>,
        ConstructorTests::RawPointerStealCtor<uint16_t, TQ::VeryLow>,
        ConstructorTests::RawPointerStealCtor<uint16_t, TQ::Low>,
        ConstructorTests::RawPointerStealCtor<uint16_t, TQ::Mid>,
        ConstructorTests::RawPointerStealCtor<uint16_t, TQ::High>,
        ConstructorTests::RawPointerStealCtor<uint32_t, TQ::None>,
        ConstructorTests::RawPointerStealCtor<uint32_t, TQ::VeryLow>,
        ConstructorTests::RawPointerStealCtor<uint32_t, TQ::Low>,
        ConstructorTests::RawPointerStealCtor<uint32_t, TQ::Mid>,
        ConstructorTests::RawPointerStealCtor<uint32_t, TQ::High>,
        ConstructorTests::RawPointerStealCtor<uint64_t, TQ::None>,
        ConstructorTests::RawPointerStealCtor<uint64_t, TQ::VeryLow>,
        ConstructorTests::RawPointerStealCtor<uint64_t, TQ::Low>,
        ConstructorTests::RawPointerStealCtor<uint64_t, TQ::Mid>,
        ConstructorTests::RawPointerStealCtor<uint64_t, TQ::High>,
        ConstructorTests::RawPointerStealCtor<Helper, TQ::None>,
        ConstructorTests::RawPointerStealCtor<Helper, TQ::VeryLow>,
        ConstructorTests::RawPointerStealCtor<Helper, TQ::Low>,
        ConstructorTests::RawPointerStealCtor<Helper, TQ::Mid>,
        ConstructorTests::RawPointerStealCtor<Helper, TQ::High>,

        ConstructorTests::CopyCtor<uint8_t, TQ::None>,
        ConstructorTests::CopyCtor<uint8_t, TQ::VeryLow>,
        ConstructorTests::CopyCtor<uint8_t, TQ::Low>,
        ConstructorTests::CopyCtor<uint8_t, TQ::Mid>,
        ConstructorTests::CopyCtor<uint8_t, TQ::High>,
        ConstructorTests::CopyCtor<uint16_t, TQ::None>,
        ConstructorTests::CopyCtor<uint16_t, TQ::VeryLow>,
        ConstructorTests::CopyCtor<uint16_t, TQ::Low>,
        ConstructorTests::CopyCtor<uint16_t, TQ::Mid>,
        ConstructorTests::CopyCtor<uint16_t, TQ::High>,
        ConstructorTests::CopyCtor<uint32_t, TQ::None>,
        ConstructorTests::CopyCtor<uint32_t, TQ::VeryLow>,
        ConstructorTests::CopyCtor<uint32_t, TQ::Low>,
        ConstructorTests::CopyCtor<uint32_t, TQ::Mid>,
        ConstructorTests::CopyCtor<uint32_t, TQ::High>,
        ConstructorTests::CopyCtor<uint64_t, TQ::None>,
        ConstructorTests::CopyCtor<uint64_t, TQ::VeryLow>,
        ConstructorTests::CopyCtor<uint64_t, TQ::Low>,
        ConstructorTests::CopyCtor<uint64_t, TQ::Mid>,
        ConstructorTests::CopyCtor<uint64_t, TQ::High>,
        ConstructorTests::CopyCtor<Helper, TQ::None>,
        ConstructorTests::CopyCtor<Helper, TQ::VeryLow>,
        ConstructorTests::CopyCtor<Helper, TQ::Low>,
        ConstructorTests::CopyCtor<Helper, TQ::Mid>,
        ConstructorTests::CopyCtor<Helper, TQ::High>,

        ConstructorTests::MoveCtor<uint8_t, TQ::None>,
        ConstructorTests::MoveCtor<uint8_t, TQ::VeryLow>,
        ConstructorTests::MoveCtor<uint8_t, TQ::Low>,
        ConstructorTests::MoveCtor<uint8_t, TQ::Mid>,
        ConstructorTests::MoveCtor<uint8_t, TQ::High>,
        ConstructorTests::MoveCtor<uint16_t, TQ::None>,
        ConstructorTests::MoveCtor<uint16_t, TQ::VeryLow>,
        ConstructorTests::MoveCtor<uint16_t, TQ::Low>,
        ConstructorTests::MoveCtor<uint16_t, TQ::Mid>,
        ConstructorTests::MoveCtor<uint16_t, TQ::High>,
        ConstructorTests::MoveCtor<uint32_t, TQ::None>,
        ConstructorTests::MoveCtor<uint32_t, TQ::VeryLow>,
        ConstructorTests::MoveCtor<uint32_t, TQ::Low>,
        ConstructorTests::MoveCtor<uint32_t, TQ::Mid>,
        ConstructorTests::MoveCtor<uint32_t, TQ::High>,
        ConstructorTests::MoveCtor<uint64_t, TQ::None>,
        ConstructorTests::MoveCtor<uint64_t, TQ::VeryLow>,
        ConstructorTests::MoveCtor<uint64_t, TQ::Low>,
        ConstructorTests::MoveCtor<uint64_t, TQ::Mid>,
        ConstructorTests::MoveCtor<uint64_t, TQ::High>,
        ConstructorTests::MoveCtor<Helper, TQ::None>,
        ConstructorTests::MoveCtor<Helper, TQ::VeryLow>,
        ConstructorTests::MoveCtor<Helper, TQ::Low>,
        ConstructorTests::MoveCtor<Helper, TQ::Mid>,
        ConstructorTests::MoveCtor<Helper, TQ::High>,

        CopyTests::CopyAssignment<uint8_t, TQ::None, TQ::None>,
        CopyTests::CopyAssignment<uint8_t, TQ::None, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint8_t, TQ::None, TQ::Low>,
        CopyTests::CopyAssignment<uint8_t, TQ::None, TQ::Mid>,
        CopyTests::CopyAssignment<uint8_t, TQ::None, TQ::High>,
        CopyTests::CopyAssignment<uint8_t, TQ::VeryLow, TQ::None>,
        CopyTests::CopyAssignment<uint8_t, TQ::VeryLow, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint8_t, TQ::VeryLow, TQ::Low>,
        CopyTests::CopyAssignment<uint8_t, TQ::VeryLow, TQ::Mid>,
        CopyTests::CopyAssignment<uint8_t, TQ::VeryLow, TQ::High>,
        CopyTests::CopyAssignment<uint8_t, TQ::Low, TQ::None>,
        CopyTests::CopyAssignment<uint8_t, TQ::Low, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint8_t, TQ::Low, TQ::Low>,
        CopyTests::CopyAssignment<uint8_t, TQ::Low, TQ::Mid>,
        CopyTests::CopyAssignment<uint8_t, TQ::Low, TQ::High>,
        CopyTests::CopyAssignment<uint8_t, TQ::Mid, TQ::None>,
        CopyTests::CopyAssignment<uint8_t, TQ::Mid, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint8_t, TQ::Mid, TQ::Low>,
        CopyTests::CopyAssignment<uint8_t, TQ::Mid, TQ::Mid>,
        CopyTests::CopyAssignment<uint8_t, TQ::Mid, TQ::High>,
        CopyTests::CopyAssignment<uint8_t, TQ::High, TQ::None>,
        CopyTests::CopyAssignment<uint8_t, TQ::High, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint8_t, TQ::High, TQ::Low>,
        CopyTests::CopyAssignment<uint8_t, TQ::High, TQ::Mid>,
        CopyTests::CopyAssignment<uint8_t, TQ::High, TQ::High>,
        CopyTests::CopyAssignment<uint16_t, TQ::None, TQ::None>,
        CopyTests::CopyAssignment<uint16_t, TQ::None, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint16_t, TQ::None, TQ::Low>,
        CopyTests::CopyAssignment<uint16_t, TQ::None, TQ::Mid>,
        CopyTests::CopyAssignment<uint16_t, TQ::None, TQ::High>,
        CopyTests::CopyAssignment<uint16_t, TQ::VeryLow, TQ::None>,
        CopyTests::CopyAssignment<uint16_t, TQ::VeryLow, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint16_t, TQ::VeryLow, TQ::Low>,
        CopyTests::CopyAssignment<uint16_t, TQ::VeryLow, TQ::Mid>,
        CopyTests::CopyAssignment<uint16_t, TQ::VeryLow, TQ::High>,
        CopyTests::CopyAssignment<uint16_t, TQ::Low, TQ::None>,
        CopyTests::CopyAssignment<uint16_t, TQ::Low, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint16_t, TQ::Low, TQ::Low>,
        CopyTests::CopyAssignment<uint16_t, TQ::Low, TQ::Mid>,
        CopyTests::CopyAssignment<uint16_t, TQ::Low, TQ::High>,
        CopyTests::CopyAssignment<uint16_t, TQ::Mid, TQ::None>,
        CopyTests::CopyAssignment<uint16_t, TQ::Mid, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint16_t, TQ::Mid, TQ::Low>,
        CopyTests::CopyAssignment<uint16_t, TQ::Mid, TQ::Mid>,
        CopyTests::CopyAssignment<uint16_t, TQ::Mid, TQ::High>,
        CopyTests::CopyAssignment<uint16_t, TQ::High, TQ::None>,
        CopyTests::CopyAssignment<uint16_t, TQ::High, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint16_t, TQ::High, TQ::Low>,
        CopyTests::CopyAssignment<uint16_t, TQ::High, TQ::Mid>,
        CopyTests::CopyAssignment<uint16_t, TQ::High, TQ::High>,
        CopyTests::CopyAssignment<uint32_t, TQ::None, TQ::None>,
        CopyTests::CopyAssignment<uint32_t, TQ::None, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint32_t, TQ::None, TQ::Low>,
        CopyTests::CopyAssignment<uint32_t, TQ::None, TQ::Mid>,
        CopyTests::CopyAssignment<uint32_t, TQ::None, TQ::High>,
        CopyTests::CopyAssignment<uint32_t, TQ::VeryLow, TQ::None>,
        CopyTests::CopyAssignment<uint32_t, TQ::VeryLow, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint32_t, TQ::VeryLow, TQ::Low>,
        CopyTests::CopyAssignment<uint32_t, TQ::VeryLow, TQ::Mid>,
        CopyTests::CopyAssignment<uint32_t, TQ::VeryLow, TQ::High>,
        CopyTests::CopyAssignment<uint32_t, TQ::Low, TQ::None>,
        CopyTests::CopyAssignment<uint32_t, TQ::Low, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint32_t, TQ::Low, TQ::Low>,
        CopyTests::CopyAssignment<uint32_t, TQ::Low, TQ::Mid>,
        CopyTests::CopyAssignment<uint32_t, TQ::Low, TQ::High>,
        CopyTests::CopyAssignment<uint32_t, TQ::Mid, TQ::None>,
        CopyTests::CopyAssignment<uint32_t, TQ::Mid, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint32_t, TQ::Mid, TQ::Low>,
        CopyTests::CopyAssignment<uint32_t, TQ::Mid, TQ::Mid>,
        CopyTests::CopyAssignment<uint32_t, TQ::Mid, TQ::High>,
        CopyTests::CopyAssignment<uint32_t, TQ::High, TQ::None>,
        CopyTests::CopyAssignment<uint32_t, TQ::High, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint32_t, TQ::High, TQ::Low>,
        CopyTests::CopyAssignment<uint32_t, TQ::High, TQ::Mid>,
        CopyTests::CopyAssignment<uint32_t, TQ::High, TQ::High>,
        CopyTests::CopyAssignment<uint64_t, TQ::None, TQ::None>,
        CopyTests::CopyAssignment<uint64_t, TQ::None, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint64_t, TQ::None, TQ::Low>,
        CopyTests::CopyAssignment<uint64_t, TQ::None, TQ::Mid>,
        CopyTests::CopyAssignment<uint64_t, TQ::None, TQ::High>,
        CopyTests::CopyAssignment<uint64_t, TQ::VeryLow, TQ::None>,
        CopyTests::CopyAssignment<uint64_t, TQ::VeryLow, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint64_t, TQ::VeryLow, TQ::Low>,
        CopyTests::CopyAssignment<uint64_t, TQ::VeryLow, TQ::Mid>,
        CopyTests::CopyAssignment<uint64_t, TQ::VeryLow, TQ::High>,
        CopyTests::CopyAssignment<uint64_t, TQ::Low, TQ::None>,
        CopyTests::CopyAssignment<uint64_t, TQ::Low, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint64_t, TQ::Low, TQ::Low>,
        CopyTests::CopyAssignment<uint64_t, TQ::Low, TQ::Mid>,
        CopyTests::CopyAssignment<uint64_t, TQ::Low, TQ::High>,
        CopyTests::CopyAssignment<uint64_t, TQ::Mid, TQ::None>,
        CopyTests::CopyAssignment<uint64_t, TQ::Mid, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint64_t, TQ::Mid, TQ::Low>,
        CopyTests::CopyAssignment<uint64_t, TQ::Mid, TQ::Mid>,
        CopyTests::CopyAssignment<uint64_t, TQ::Mid, TQ::High>,
        CopyTests::CopyAssignment<uint64_t, TQ::High, TQ::None>,
        CopyTests::CopyAssignment<uint64_t, TQ::High, TQ::VeryLow>,
        CopyTests::CopyAssignment<uint64_t, TQ::High, TQ::Low>,
        CopyTests::CopyAssignment<uint64_t, TQ::High, TQ::Mid>,
        CopyTests::CopyAssignment<uint64_t, TQ::High, TQ::High>,
        CopyTests::CopyAssignment<Helper, TQ::None, TQ::None>,
        CopyTests::CopyAssignment<Helper, TQ::None, TQ::VeryLow>,
        CopyTests::CopyAssignment<Helper, TQ::None, TQ::Low>,
        CopyTests::CopyAssignment<Helper, TQ::None, TQ::Mid>,
        CopyTests::CopyAssignment<Helper, TQ::None, TQ::High>,
        CopyTests::CopyAssignment<Helper, TQ::VeryLow, TQ::None>,
        CopyTests::CopyAssignment<Helper, TQ::VeryLow, TQ::VeryLow>,
        CopyTests::CopyAssignment<Helper, TQ::VeryLow, TQ::Low>,
        CopyTests::CopyAssignment<Helper, TQ::VeryLow, TQ::Mid>,
        CopyTests::CopyAssignment<Helper, TQ::VeryLow, TQ::High>,
        CopyTests::CopyAssignment<Helper, TQ::Low, TQ::None>,
        CopyTests::CopyAssignment<Helper, TQ::Low, TQ::VeryLow>,
        CopyTests::CopyAssignment<Helper, TQ::Low, TQ::Low>,
        CopyTests::CopyAssignment<Helper, TQ::Low, TQ::Mid>,
        CopyTests::CopyAssignment<Helper, TQ::Low, TQ::High>,
        CopyTests::CopyAssignment<Helper, TQ::Mid, TQ::None>,
        CopyTests::CopyAssignment<Helper, TQ::Mid, TQ::VeryLow>,
        CopyTests::CopyAssignment<Helper, TQ::Mid, TQ::Low>,
        CopyTests::CopyAssignment<Helper, TQ::Mid, TQ::Mid>,
        CopyTests::CopyAssignment<Helper, TQ::Mid, TQ::High>,
        CopyTests::CopyAssignment<Helper, TQ::High, TQ::None>,
        CopyTests::CopyAssignment<Helper, TQ::High, TQ::VeryLow>,
        CopyTests::CopyAssignment<Helper, TQ::High, TQ::Low>,
        CopyTests::CopyAssignment<Helper, TQ::High, TQ::Mid>,
        CopyTests::CopyAssignment<Helper, TQ::High, TQ::High>,

        MoveTests::MoveAssignment<uint8_t, TQ::None, TQ::None>,
        MoveTests::MoveAssignment<uint8_t, TQ::None, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint8_t, TQ::None, TQ::Low>,
        MoveTests::MoveAssignment<uint8_t, TQ::None, TQ::Mid>,
        MoveTests::MoveAssignment<uint8_t, TQ::None, TQ::High>,
        MoveTests::MoveAssignment<uint8_t, TQ::VeryLow, TQ::None>,
        MoveTests::MoveAssignment<uint8_t, TQ::VeryLow, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint8_t, TQ::VeryLow, TQ::Low>,
        MoveTests::MoveAssignment<uint8_t, TQ::VeryLow, TQ::Mid>,
        MoveTests::MoveAssignment<uint8_t, TQ::VeryLow, TQ::High>,
        MoveTests::MoveAssignment<uint8_t, TQ::Low, TQ::None>,
        MoveTests::MoveAssignment<uint8_t, TQ::Low, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint8_t, TQ::Low, TQ::Low>,
        MoveTests::MoveAssignment<uint8_t, TQ::Low, TQ::Mid>,
        MoveTests::MoveAssignment<uint8_t, TQ::Low, TQ::High>,
        MoveTests::MoveAssignment<uint8_t, TQ::Mid, TQ::None>,
        MoveTests::MoveAssignment<uint8_t, TQ::Mid, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint8_t, TQ::Mid, TQ::Low>,
        MoveTests::MoveAssignment<uint8_t, TQ::Mid, TQ::Mid>,
        MoveTests::MoveAssignment<uint8_t, TQ::Mid, TQ::High>,
        MoveTests::MoveAssignment<uint8_t, TQ::High, TQ::None>,
        MoveTests::MoveAssignment<uint8_t, TQ::High, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint8_t, TQ::High, TQ::Low>,
        MoveTests::MoveAssignment<uint8_t, TQ::High, TQ::Mid>,
        MoveTests::MoveAssignment<uint8_t, TQ::High, TQ::High>,
        MoveTests::MoveAssignment<uint16_t, TQ::None, TQ::None>,
        MoveTests::MoveAssignment<uint16_t, TQ::None, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint16_t, TQ::None, TQ::Low>,
        MoveTests::MoveAssignment<uint16_t, TQ::None, TQ::Mid>,
        MoveTests::MoveAssignment<uint16_t, TQ::None, TQ::High>,
        MoveTests::MoveAssignment<uint16_t, TQ::VeryLow, TQ::None>,
        MoveTests::MoveAssignment<uint16_t, TQ::VeryLow, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint16_t, TQ::VeryLow, TQ::Low>,
        MoveTests::MoveAssignment<uint16_t, TQ::VeryLow, TQ::Mid>,
        MoveTests::MoveAssignment<uint16_t, TQ::VeryLow, TQ::High>,
        MoveTests::MoveAssignment<uint16_t, TQ::Low, TQ::None>,
        MoveTests::MoveAssignment<uint16_t, TQ::Low, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint16_t, TQ::Low, TQ::Low>,
        MoveTests::MoveAssignment<uint16_t, TQ::Low, TQ::Mid>,
        MoveTests::MoveAssignment<uint16_t, TQ::Low, TQ::High>,
        MoveTests::MoveAssignment<uint16_t, TQ::Mid, TQ::None>,
        MoveTests::MoveAssignment<uint16_t, TQ::Mid, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint16_t, TQ::Mid, TQ::Low>,
        MoveTests::MoveAssignment<uint16_t, TQ::Mid, TQ::Mid>,
        MoveTests::MoveAssignment<uint16_t, TQ::Mid, TQ::High>,
        MoveTests::MoveAssignment<uint16_t, TQ::High, TQ::None>,
        MoveTests::MoveAssignment<uint16_t, TQ::High, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint16_t, TQ::High, TQ::Low>,
        MoveTests::MoveAssignment<uint16_t, TQ::High, TQ::Mid>,
        MoveTests::MoveAssignment<uint16_t, TQ::High, TQ::High>,
        MoveTests::MoveAssignment<uint32_t, TQ::None, TQ::None>,
        MoveTests::MoveAssignment<uint32_t, TQ::None, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint32_t, TQ::None, TQ::Low>,
        MoveTests::MoveAssignment<uint32_t, TQ::None, TQ::Mid>,
        MoveTests::MoveAssignment<uint32_t, TQ::None, TQ::High>,
        MoveTests::MoveAssignment<uint32_t, TQ::VeryLow, TQ::None>,
        MoveTests::MoveAssignment<uint32_t, TQ::VeryLow, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint32_t, TQ::VeryLow, TQ::Low>,
        MoveTests::MoveAssignment<uint32_t, TQ::VeryLow, TQ::Mid>,
        MoveTests::MoveAssignment<uint32_t, TQ::VeryLow, TQ::High>,
        MoveTests::MoveAssignment<uint32_t, TQ::Low, TQ::None>,
        MoveTests::MoveAssignment<uint32_t, TQ::Low, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint32_t, TQ::Low, TQ::Low>,
        MoveTests::MoveAssignment<uint32_t, TQ::Low, TQ::Mid>,
        MoveTests::MoveAssignment<uint32_t, TQ::Low, TQ::High>,
        MoveTests::MoveAssignment<uint32_t, TQ::Mid, TQ::None>,
        MoveTests::MoveAssignment<uint32_t, TQ::Mid, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint32_t, TQ::Mid, TQ::Low>,
        MoveTests::MoveAssignment<uint32_t, TQ::Mid, TQ::Mid>,
        MoveTests::MoveAssignment<uint32_t, TQ::Mid, TQ::High>,
        MoveTests::MoveAssignment<uint32_t, TQ::High, TQ::None>,
        MoveTests::MoveAssignment<uint32_t, TQ::High, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint32_t, TQ::High, TQ::Low>,
        MoveTests::MoveAssignment<uint32_t, TQ::High, TQ::Mid>,
        MoveTests::MoveAssignment<uint32_t, TQ::High, TQ::High>,
        MoveTests::MoveAssignment<uint64_t, TQ::None, TQ::None>,
        MoveTests::MoveAssignment<uint64_t, TQ::None, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint64_t, TQ::None, TQ::Low>,
        MoveTests::MoveAssignment<uint64_t, TQ::None, TQ::Mid>,
        MoveTests::MoveAssignment<uint64_t, TQ::None, TQ::High>,
        MoveTests::MoveAssignment<uint64_t, TQ::VeryLow, TQ::None>,
        MoveTests::MoveAssignment<uint64_t, TQ::VeryLow, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint64_t, TQ::VeryLow, TQ::Low>,
        MoveTests::MoveAssignment<uint64_t, TQ::VeryLow, TQ::Mid>,
        MoveTests::MoveAssignment<uint64_t, TQ::VeryLow, TQ::High>,
        MoveTests::MoveAssignment<uint64_t, TQ::Low, TQ::None>,
        MoveTests::MoveAssignment<uint64_t, TQ::Low, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint64_t, TQ::Low, TQ::Low>,
        MoveTests::MoveAssignment<uint64_t, TQ::Low, TQ::Mid>,
        MoveTests::MoveAssignment<uint64_t, TQ::Low, TQ::High>,
        MoveTests::MoveAssignment<uint64_t, TQ::Mid, TQ::None>,
        MoveTests::MoveAssignment<uint64_t, TQ::Mid, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint64_t, TQ::Mid, TQ::Low>,
        MoveTests::MoveAssignment<uint64_t, TQ::Mid, TQ::Mid>,
        MoveTests::MoveAssignment<uint64_t, TQ::Mid, TQ::High>,
        MoveTests::MoveAssignment<uint64_t, TQ::High, TQ::None>,
        MoveTests::MoveAssignment<uint64_t, TQ::High, TQ::VeryLow>,
        MoveTests::MoveAssignment<uint64_t, TQ::High, TQ::Low>,
        MoveTests::MoveAssignment<uint64_t, TQ::High, TQ::Mid>,
        MoveTests::MoveAssignment<uint64_t, TQ::High, TQ::High>,
        MoveTests::MoveAssignment<Helper, TQ::None, TQ::None>,
        MoveTests::MoveAssignment<Helper, TQ::None, TQ::VeryLow>,
        MoveTests::MoveAssignment<Helper, TQ::None, TQ::Low>,
        MoveTests::MoveAssignment<Helper, TQ::None, TQ::Mid>,
        MoveTests::MoveAssignment<Helper, TQ::None, TQ::High>,
        MoveTests::MoveAssignment<Helper, TQ::VeryLow, TQ::None>,
        MoveTests::MoveAssignment<Helper, TQ::VeryLow, TQ::VeryLow>,
        MoveTests::MoveAssignment<Helper, TQ::VeryLow, TQ::Low>,
        MoveTests::MoveAssignment<Helper, TQ::VeryLow, TQ::Mid>,
        MoveTests::MoveAssignment<Helper, TQ::VeryLow, TQ::High>,
        MoveTests::MoveAssignment<Helper, TQ::Low, TQ::None>,
        MoveTests::MoveAssignment<Helper, TQ::Low, TQ::VeryLow>,
        MoveTests::MoveAssignment<Helper, TQ::Low, TQ::Low>,
        MoveTests::MoveAssignment<Helper, TQ::Low, TQ::Mid>,
        MoveTests::MoveAssignment<Helper, TQ::Low, TQ::High>,
        MoveTests::MoveAssignment<Helper, TQ::Mid, TQ::None>,
        MoveTests::MoveAssignment<Helper, TQ::Mid, TQ::VeryLow>,
        MoveTests::MoveAssignment<Helper, TQ::Mid, TQ::Low>,
        MoveTests::MoveAssignment<Helper, TQ::Mid, TQ::Mid>,
        MoveTests::MoveAssignment<Helper, TQ::Mid, TQ::High>,
        MoveTests::MoveAssignment<Helper, TQ::High, TQ::None>,
        MoveTests::MoveAssignment<Helper, TQ::High, TQ::VeryLow>,
        MoveTests::MoveAssignment<Helper, TQ::High, TQ::Low>,
        MoveTests::MoveAssignment<Helper, TQ::High, TQ::Mid>,
        MoveTests::MoveAssignment<Helper, TQ::High, TQ::High>,

        DereferenceOperatorTests::Dereference<uint8_t, TQ::None>,
        DereferenceOperatorTests::Dereference<uint8_t, TQ::VeryLow>,
        DereferenceOperatorTests::Dereference<uint8_t, TQ::Low>,
        DereferenceOperatorTests::Dereference<uint8_t, TQ::Mid>,
        DereferenceOperatorTests::Dereference<uint8_t, TQ::High>,
        DereferenceOperatorTests::Dereference<uint16_t, TQ::None>,
        DereferenceOperatorTests::Dereference<uint16_t, TQ::VeryLow>,
        DereferenceOperatorTests::Dereference<uint16_t, TQ::Low>,
        DereferenceOperatorTests::Dereference<uint16_t, TQ::Mid>,
        DereferenceOperatorTests::Dereference<uint16_t, TQ::High>,
        DereferenceOperatorTests::Dereference<uint32_t, TQ::None>,
        DereferenceOperatorTests::Dereference<uint32_t, TQ::VeryLow>,
        DereferenceOperatorTests::Dereference<uint32_t, TQ::Low>,
        DereferenceOperatorTests::Dereference<uint32_t, TQ::Mid>,
        DereferenceOperatorTests::Dereference<uint32_t, TQ::High>,
        DereferenceOperatorTests::Dereference<uint64_t, TQ::None>,
        DereferenceOperatorTests::Dereference<uint64_t, TQ::VeryLow>,
        DereferenceOperatorTests::Dereference<uint64_t, TQ::Low>,
        DereferenceOperatorTests::Dereference<uint64_t, TQ::Mid>,
        DereferenceOperatorTests::Dereference<uint64_t, TQ::High>,
        DereferenceOperatorTests::Dereference<Helper, TQ::None>,
        DereferenceOperatorTests::Dereference<Helper, TQ::VeryLow>,
        DereferenceOperatorTests::Dereference<Helper, TQ::Low>,
        DereferenceOperatorTests::Dereference<Helper, TQ::Mid>,
        DereferenceOperatorTests::Dereference<Helper, TQ::High>
    };

    return tests;
}