#include <CCPointerCommonHelpersTests.h>

CC::PointerCommonHelpersTests::UTList CC::PointerCommonHelpersTests::GetTests( )
{
    using TQ = TestQuantity;

    static const UTList tests
    {
        CopyToRawPointer<uint8_t, TQ::Zero>,
        CopyToRawPointer<uint8_t, TQ::One>,
        CopyToRawPointer<uint8_t, TQ::Many>,
        CopyToRawPointer<uint16_t, TQ::Zero>,
        CopyToRawPointer<uint16_t, TQ::One>,
        CopyToRawPointer<uint16_t, TQ::Many>,
        CopyToRawPointer<uint32_t, TQ::Zero>,
        CopyToRawPointer<uint32_t, TQ::One>,
        CopyToRawPointer<uint32_t, TQ::Many>,
        CopyToRawPointer<uint64_t, TQ::Zero>,
        CopyToRawPointer<uint64_t, TQ::One>,
        CopyToRawPointer<uint64_t, TQ::Many>,
        CopyToRawPointer<Helper, TQ::Zero>,
        CopyToRawPointer<Helper, TQ::One>,
        CopyToRawPointer<Helper, TQ::Many>,

        MoveToRawPointer<uint8_t, TQ::Zero>,
        MoveToRawPointer<uint8_t, TQ::One>,
        MoveToRawPointer<uint8_t, TQ::Many>,
        MoveToRawPointer<uint16_t, TQ::Zero>,
        MoveToRawPointer<uint16_t, TQ::One>,
        MoveToRawPointer<uint16_t, TQ::Many>,
        MoveToRawPointer<uint32_t, TQ::Zero>,
        MoveToRawPointer<uint32_t, TQ::One>,
        MoveToRawPointer<uint32_t, TQ::Many>,
        MoveToRawPointer<uint64_t, TQ::Zero>,
        MoveToRawPointer<uint64_t, TQ::One>,
        MoveToRawPointer<uint64_t, TQ::Many>,
        MoveToRawPointer<Helper, TQ::Zero>,
        MoveToRawPointer<Helper, TQ::One>,
        MoveToRawPointer<Helper, TQ::Many>,

        Allocate<uint8_t, TQ::Zero>,
        Allocate<uint8_t, TQ::One>,
        Allocate<uint8_t, TQ::Many>,
        Allocate<uint16_t, TQ::Zero>,
        Allocate<uint16_t, TQ::One>,
        Allocate<uint16_t, TQ::Many>,
        Allocate<uint32_t, TQ::Zero>,
        Allocate<uint32_t, TQ::One>,
        Allocate<uint32_t, TQ::Many>,
        Allocate<uint64_t, TQ::Zero>,
        Allocate<uint64_t, TQ::One>,
        Allocate<uint64_t, TQ::Many>,
        Allocate<Helper, TQ::Zero>,
        Allocate<Helper, TQ::One>,
        Allocate<Helper, TQ::Many>,

        AllocateFromRawPointer<uint8_t, TQ::Zero>,
        AllocateFromRawPointer<uint8_t, TQ::One>,
        AllocateFromRawPointer<uint8_t, TQ::Many>,
        AllocateFromRawPointer<uint16_t, TQ::Zero>,
        AllocateFromRawPointer<uint16_t, TQ::One>,
        AllocateFromRawPointer<uint16_t, TQ::Many>,
        AllocateFromRawPointer<uint32_t, TQ::Zero>,
        AllocateFromRawPointer<uint32_t, TQ::One>,
        AllocateFromRawPointer<uint32_t, TQ::Many>,
        AllocateFromRawPointer<uint64_t, TQ::Zero>,
        AllocateFromRawPointer<uint64_t, TQ::One>,
        AllocateFromRawPointer<uint64_t, TQ::Many>,
        AllocateFromRawPointer<Helper, TQ::Zero>,
        AllocateFromRawPointer<Helper, TQ::One>,
        AllocateFromRawPointer<Helper, TQ::Many>,

        AllocateFromIPointerObj<uint8_t, TQ::Zero>,
        AllocateFromIPointerObj<uint8_t, TQ::One>,
        AllocateFromIPointerObj<uint8_t, TQ::Many>,
        AllocateFromIPointerObj<uint16_t, TQ::Zero>,
        AllocateFromIPointerObj<uint16_t, TQ::One>,
        AllocateFromIPointerObj<uint16_t, TQ::Many>,
        AllocateFromIPointerObj<uint32_t, TQ::Zero>,
        AllocateFromIPointerObj<uint32_t, TQ::One>,
        AllocateFromIPointerObj<uint32_t, TQ::Many>,
        AllocateFromIPointerObj<uint64_t, TQ::Zero>,
        AllocateFromIPointerObj<uint64_t, TQ::One>,
        AllocateFromIPointerObj<uint64_t, TQ::Many>,
        AllocateFromIPointerObj<Helper, TQ::Zero>,
        AllocateFromIPointerObj<Helper, TQ::One>,
        AllocateFromIPointerObj<Helper, TQ::Many>
    };

    return tests;
}