#include <CCStringUtilTests.h>

std::list<CC::StringUtilTests::UTFunc> CC::StringUtilTests::GetTests( )
{
    static const std::list<std::function<UTR(void)>> tests
    {
        EnumValidatorTests::InvalidOperationType,
        EnumValidatorTests::ValidOperationType,
        EnumValidatorTests::InvalidEarlyExitResult,
        EnumValidatorTests::ValidEarlyExitResult,
        EnumValidatorTests::InvalidReturnType,
        EnumValidatorTests::ValidReturnType,
        EnumValidatorTests::InvalidBaseType,
        EnumValidatorTests::ValidBaseType,

        BuildBufferTests::ZeroLength<RT::CppString, char>,
        BuildBufferTests::ZeroLength<RT::CppString, wchar_t>,
        BuildBufferTests::ZeroLength<RT::CCBuffer, char>,
        BuildBufferTests::ZeroLength<RT::CCBuffer, wchar_t>,
        BuildBufferTests::OneLength<RT::CppString, char>,
        BuildBufferTests::OneLength<RT::CppString, wchar_t>,
        BuildBufferTests::OneLength<RT::CCBuffer, char>,
        BuildBufferTests::OneLength<RT::CCBuffer, wchar_t>,
        BuildBufferTests::ManyLength<RT::CppString, char>,
        BuildBufferTests::ManyLength<RT::CppString, wchar_t>,
        BuildBufferTests::ManyLength<RT::CCBuffer, char>,
        BuildBufferTests::ManyLength<RT::CCBuffer, wchar_t>,

        GetLengthTests::NullptrArg<char>,
        GetLengthTests::NullptrArg<wchar_t>,
        GetLengthTests::ZeroLength<char>,
        GetLengthTests::ZeroLength<wchar_t>,
        GetLengthTests::OneLength<char>,
        GetLengthTests::OneLength<wchar_t>,
        GetLengthTests::ManyLength<char>,
        GetLengthTests::ManyLength<wchar_t>,

        ComparisonEarlyExitTests::SameLengthDifferentStrs<char>,
        ComparisonEarlyExitTests::SameLengthDifferentStrs<wchar_t>,
        ComparisonEarlyExitTests::SameStr<char>,
        ComparisonEarlyExitTests::SameStr<wchar_t>,
        ComparisonEarlyExitTests::LengthMismatch<char>,
        ComparisonEarlyExitTests::LengthMismatch<wchar_t>,
        ComparisonEarlyExitTests::BothZeroLength<char>,
        ComparisonEarlyExitTests::BothZeroLength<wchar_t>,
        ComparisonEarlyExitTests::OneNullptr<char>,
        ComparisonEarlyExitTests::OneNullptr<wchar_t>,
        ComparisonEarlyExitTests::BothNullptr<char>,
        ComparisonEarlyExitTests::BothNullptr<wchar_t>,
        ComparisonEarlyExitTests::SamePtr<char>,
        ComparisonEarlyExitTests::SamePtr<wchar_t>,

        ComparisonTests::LengthMismatch<char>,
        ComparisonTests::LengthMismatch<wchar_t>,
        ComparisonTests::BothZeroLength<char>,
        ComparisonTests::BothZeroLength<wchar_t>,
        ComparisonTests::OneNullptr<char>,
        ComparisonTests::OneNullptr<wchar_t>,
        ComparisonTests::BothNullptr<char>,
        ComparisonTests::BothNullptr<wchar_t>,
        ComparisonTests::SamePtr<char>,
        ComparisonTests::SamePtr<wchar_t>,
        ComparisonTests::CaseInsensitiveNoMatch<char>,
        ComparisonTests::CaseInsensitiveNoMatch<wchar_t>,
        ComparisonTests::CaseInsensitiveDifferentCasing<char>,
        ComparisonTests::CaseInsensitiveDifferentCasing<wchar_t>,
        ComparisonTests::CaseInsensitiveMatch<char>,
        ComparisonTests::CaseInsensitiveMatch<wchar_t>,
        ComparisonTests::CaseSensitiveNoMatch<char>,
        ComparisonTests::CaseSensitiveNoMatch<wchar_t>,
        ComparisonTests::CaseSensitiveDifferentCasing<char>,
        ComparisonTests::CaseSensitiveDifferentCasing<wchar_t>,
        ComparisonTests::CaseSensitiveMatch<char>,
        ComparisonTests::CaseSensitiveMatch<wchar_t>,

        CopyEarlyExitTests::Nullptr<RT::CppString, char>,
        CopyEarlyExitTests::Nullptr<RT::CppString, wchar_t>,
        CopyEarlyExitTests::Nullptr<RT::CCBuffer, char>,
        CopyEarlyExitTests::Nullptr<RT::CCBuffer, wchar_t>,
        CopyEarlyExitTests::ZeroLength<RT::CppString, char>,
        CopyEarlyExitTests::ZeroLength<RT::CppString, wchar_t>,
        CopyEarlyExitTests::ZeroLength<RT::CCBuffer, char>,
        CopyEarlyExitTests::ZeroLength<RT::CCBuffer, wchar_t>,
        CopyEarlyExitTests::OneLength<RT::CppString, char>,
        CopyEarlyExitTests::OneLength<RT::CppString, wchar_t>,
        CopyEarlyExitTests::OneLength<RT::CCBuffer, char>,
        CopyEarlyExitTests::OneLength<RT::CCBuffer, wchar_t>,
        CopyEarlyExitTests::ManyLength<RT::CppString, char>,
        CopyEarlyExitTests::ManyLength<RT::CppString, wchar_t>,
        CopyEarlyExitTests::ManyLength<RT::CCBuffer, char>,
        CopyEarlyExitTests::ManyLength<RT::CCBuffer, wchar_t>,

        CopyTests::Nullptr<RT::CppString, char>,
        CopyTests::Nullptr<RT::CppString, wchar_t>,
        CopyTests::Nullptr<RT::CCBuffer, char>,
        CopyTests::Nullptr<RT::CCBuffer, wchar_t>,
        CopyTests::ZeroLength<RT::CppString, char>,
        CopyTests::ZeroLength<RT::CppString, wchar_t>,
        CopyTests::ZeroLength<RT::CCBuffer, char>,
        CopyTests::ZeroLength<RT::CCBuffer, wchar_t>,
        CopyTests::OneLength<RT::CppString, char>,
        CopyTests::OneLength<RT::CppString, wchar_t>,
        CopyTests::OneLength<RT::CCBuffer, char>,
        CopyTests::OneLength<RT::CCBuffer, wchar_t>,
        CopyTests::ManyLength<RT::CppString, char>,
        CopyTests::ManyLength<RT::CppString, wchar_t>,
        CopyTests::ManyLength<RT::CCBuffer, char>,
        CopyTests::ManyLength<RT::CCBuffer, wchar_t>,

        UTFConversionEarlyExitTests::Nullptr<RT::CppString, char>,
        UTFConversionEarlyExitTests::Nullptr<RT::CppString, wchar_t>,
        UTFConversionEarlyExitTests::Nullptr<RT::CCBuffer, char>,
        UTFConversionEarlyExitTests::Nullptr<RT::CCBuffer, wchar_t>,
        UTFConversionEarlyExitTests::ZeroLength<RT::CppString, char>,
        UTFConversionEarlyExitTests::ZeroLength<RT::CppString, wchar_t>,
        UTFConversionEarlyExitTests::ZeroLength<RT::CCBuffer, char>,
        UTFConversionEarlyExitTests::ZeroLength<RT::CCBuffer, wchar_t>,
        UTFConversionEarlyExitTests::OneLength<RT::CppString, char>,
        UTFConversionEarlyExitTests::OneLength<RT::CppString, wchar_t>,
        UTFConversionEarlyExitTests::OneLength<RT::CCBuffer, char>,
        UTFConversionEarlyExitTests::OneLength<RT::CCBuffer, wchar_t>,
        UTFConversionEarlyExitTests::ManyLength<RT::CppString, char>,
        UTFConversionEarlyExitTests::ManyLength<RT::CppString, wchar_t>,
        UTFConversionEarlyExitTests::ManyLength<RT::CCBuffer, char>,
        UTFConversionEarlyExitTests::ManyLength<RT::CCBuffer, wchar_t>,

        UTFConversionTests::Nullptr<RT::CppString, char, char>,
        UTFConversionTests::Nullptr<RT::CppString, char, wchar_t>,
        UTFConversionTests::Nullptr<RT::CppString, wchar_t, char>,
        UTFConversionTests::Nullptr<RT::CppString, wchar_t, wchar_t>,
        UTFConversionTests::Nullptr<RT::CCBuffer, char, char>,
        UTFConversionTests::Nullptr<RT::CCBuffer, char, wchar_t>,
        UTFConversionTests::Nullptr<RT::CCBuffer, wchar_t, char>,
        UTFConversionTests::Nullptr<RT::CCBuffer, wchar_t, wchar_t>,
        UTFConversionTests::ZeroLength<RT::CppString, char, char>,
        UTFConversionTests::ZeroLength<RT::CppString, char, wchar_t>,
        UTFConversionTests::ZeroLength<RT::CppString, wchar_t, char>,
        UTFConversionTests::ZeroLength<RT::CppString, wchar_t, wchar_t>,
        UTFConversionTests::ZeroLength<RT::CCBuffer, char, char>,
        UTFConversionTests::ZeroLength<RT::CCBuffer, char, wchar_t>,
        UTFConversionTests::ZeroLength<RT::CCBuffer, wchar_t, char>,
        UTFConversionTests::ZeroLength<RT::CCBuffer, wchar_t, wchar_t>,
        UTFConversionTests::OneLength<RT::CppString, char, char>,
        UTFConversionTests::OneLength<RT::CppString, char, wchar_t>,
        UTFConversionTests::OneLength<RT::CppString, wchar_t, char>,
        UTFConversionTests::OneLength<RT::CppString, wchar_t, wchar_t>,
        UTFConversionTests::OneLength<RT::CCBuffer, char, char>,
        UTFConversionTests::OneLength<RT::CCBuffer, char, wchar_t>,
        UTFConversionTests::OneLength<RT::CCBuffer, wchar_t, char>,
        UTFConversionTests::OneLength<RT::CCBuffer, wchar_t, wchar_t>,
        UTFConversionTests::ManyLength<RT::CppString, char, char>,
        UTFConversionTests::ManyLength<RT::CppString, char, wchar_t>,
        UTFConversionTests::ManyLength<RT::CppString, wchar_t, char>,
        UTFConversionTests::ManyLength<RT::CppString, wchar_t, wchar_t>,
        UTFConversionTests::ManyLength<RT::CCBuffer, char, char>,
        UTFConversionTests::ManyLength<RT::CCBuffer, char, wchar_t>,
        UTFConversionTests::ManyLength<RT::CCBuffer, wchar_t, char>,
        UTFConversionTests::ManyLength<RT::CCBuffer, wchar_t, wchar_t>,

        NumberConversionTests::NumberType<RT::CppString, BT::Binary, int8_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, int8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, int8_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, int8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, int8_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, int8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, int8_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, int8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, uint8_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, uint8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, uint8_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, uint8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, uint8_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, uint8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, uint8_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, uint8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, int16_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, int16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, int16_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, int16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, int16_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, int16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, int16_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, int16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, uint16_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, uint16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, uint16_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, uint16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, uint16_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, uint16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, uint16_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, uint16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, int32_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, int32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, int32_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, int32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, int32_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, int32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, int32_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, int32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, uint32_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, uint32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, uint32_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, uint32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, uint32_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, uint32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, uint32_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, uint32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, int64_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, int64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, int64_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, int64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, int64_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, int64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, int64_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, int64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, uint64_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, uint64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, uint64_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, uint64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, uint64_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, uint64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, uint64_t, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, uint64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, void*, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Binary, void*, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, void*, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Octal, void*, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, void*, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Decimal, void*, wchar_t>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, void*, char>,
        NumberConversionTests::NumberType<RT::CppString, BT::Hexadecimal, void*, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, int8_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, int8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, int8_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, int8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, int8_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, int8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, int8_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, int8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, uint8_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, uint8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, uint8_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, uint8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, uint8_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, uint8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, uint8_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, uint8_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, int16_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, int16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, int16_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, int16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, int16_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, int16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, int16_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, int16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, uint16_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, uint16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, uint16_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, uint16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, uint16_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, uint16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, uint16_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, uint16_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, int32_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, int32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, int32_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, int32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, int32_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, int32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, int32_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, int32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, uint32_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, uint32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, uint32_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, uint32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, uint32_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, uint32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, uint32_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, uint32_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, int64_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, int64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, int64_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, int64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, int64_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, int64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, int64_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, int64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, uint64_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, uint64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, uint64_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, uint64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, uint64_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, uint64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, uint64_t, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, uint64_t, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, void*, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Binary, void*, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, void*, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Octal, void*, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, void*, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Decimal, void*, wchar_t>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, void*, char>,
        NumberConversionTests::NumberType<RT::CCBuffer, BT::Hexadecimal, void*, wchar_t>
    };

    return tests;
}
